startState: s32'dmy'
  sprite: s32'null', 1
  endState: 

startState: s32'SlowNeeldeObjLand'
  upon: (IMMEDIATE)
    Unknown244: 
    attackLevel: 2
    damage: 22
    setAttachOpponent: 1
    setProration: 90
    Unknown2178: 
    numberOfHits: 1
    Unknown2189: 1
    Unknown2180: 1
    Unknown2181: 1
    Unknown2182: 1
    Unknown2183: 1
    Unknown58: 1
    setThrowRange: 0
    upon: 45
      Unknown448: s32'rvn_401EffEnd', 100
      Unknown14: s32'End'
      endUpon: 
    upon: 35
      Unknown2176: 23
      endUpon: 
    upon: (HIT)
      if: (VARIABLE), 45
        Unknown32: s32'SlowEffect'
        Unknown2247: 0, 1, 0, 0
        callEtcState: s32'SlowEffect', 100
        endIf: 
      else: 
        Unknown32: s32'SlowEffect'
        Unknown2247: 0, 0, 0, 0
        callEtcState: s32'SlowEffect', 100
        endElse: 
      endUpon: 
    upon: 66
      storeValue: (VARIABLE), 45, (STATIC), 1
      endUpon: 
    upon: 2
      Unknown2176: 23
      endUpon: 
    Unknown1602: 1
    endUpon: 
  sprite: s32'null', 6
  setMarker: s32'Jizoku'
  sprite: s32'rvn_SlowNeedleObj', 2
  ifOperation: (IS_EQUAL), (VARIABLE), 115, (STATIC), 0
    physicsXImpulse: 18000
    physicsYImpulse: -36000
    Unknown164: -60000
    endIf: 
  ifOperation: (IS_EQUAL), (VARIABLE), 115, (STATIC), 1
    physicsXImpulse: 38000
    physicsYImpulse: -15000
    Unknown164: -21000
    endIf: 
  ifOperation: (IS_EQUAL), (VARIABLE), 115, (STATIC), 2
    physicsXImpulse: 38000
    endIf: 
  Unknown450: s32'rvn_401EffJizoku'
  hit: 
  createObject2: s32'rvn401EffNokosi', 100
  Unknown157: -100
  sprite: s32'rvn_SlowNeedleObj', 2
  Unknown157: 100
  sprite: s32'rvn_SlowNeedleObj', 2
  Unknown157: -100
  sprite: s32'rvn_SlowNeedleObj', 2
  Unknown157: 100
  goToMarker: s32'Jizoku'
  setMarker: s32'End'
  sprite: s32'null', 14
  Unknown176: 1
  Unknown450: s32'CN_Null'
  endState: 

startState: s32'SlowNeeldeObjAir'
  upon: (IMMEDIATE)
    Unknown244: 
    attackLevel: 2
    damage: 22
    setAttachOpponent: 1
    setProration: 90
    Unknown2178: 
    numberOfHits: 1
    Unknown2189: 1
    Unknown2180: 1
    Unknown2181: 1
    Unknown2182: 1
    Unknown2183: 1
    setThrowRange: 0
    upon: 45
      Unknown448: s32'rvn_401EffEnd', 100
      Unknown14: s32'End'
      endUpon: 
    upon: 35
      Unknown2176: 23
      endUpon: 
    upon: (HIT)
      if: (VARIABLE), 45
        Unknown32: s32'SlowEffect'
        Unknown2247: 0, 1, 0, 0
        callEtcState: s32'SlowEffect', 100
        endIf: 
      else: 
        Unknown32: s32'SlowEffect'
        Unknown2247: 0, 0, 0, 0
        callEtcState: s32'SlowEffect', 100
        endElse: 
      endUpon: 
    upon: 66
      storeValue: (VARIABLE), 45, (STATIC), 1
      endUpon: 
    upon: 2
      Unknown2176: 23
      endUpon: 
    Unknown1602: 1
    endUpon: 
  sprite: s32'null', 6
  setMarker: s32'Jizoku'
  sprite: s32'rvn_SlowNeedleObj', 2
  ifOperation: (IS_EQUAL), (VARIABLE), 115, (STATIC), 0
    physicsXImpulse: 18000
    physicsYImpulse: -36000
    Unknown164: -60000
    endIf: 
  ifOperation: (IS_EQUAL), (VARIABLE), 115, (STATIC), 1
    physicsXImpulse: 38000
    physicsYImpulse: -15000
    Unknown164: -21000
    endIf: 
  ifOperation: (IS_EQUAL), (VARIABLE), 115, (STATIC), 2
    physicsXImpulse: 30000
    physicsYImpulse: -25000
    Unknown164: -38000
    endIf: 
  Unknown450: s32'rvn_401EffJizoku'
  hit: 
  createObject2: s32'rvn401EffNokosi', 100
  Unknown157: -100
  sprite: s32'rvn_SlowNeedleObj', 2
  Unknown157: 100
  sprite: s32'rvn_SlowNeedleObj', 2
  Unknown157: -100
  sprite: s32'rvn_SlowNeedleObj', 2
  Unknown157: 100
  goToMarker: s32'Jizoku'
  setMarker: s32'End'
  sprite: s32'null', 14
  Unknown176: 1
  Unknown450: s32'CN_Null'
  endState: 

startState: s32'SlowEffect'
  upon: (IMMEDIATE)
    Unknown454: 22
    upon: (BEFORE_EXIT)
      Unknown1771: s32'401EffDebuff', 23
      ifOperation: (IS_EQUAL), (VARIABLE), 115, (STATIC), 0
        Unknown41: 22
        storeValue: (VARIABLE), 229, (STATIC), 100
        Unknown40: 
        endIf: 
      ifOperation: (IS_EQUAL), (VARIABLE), 115, (STATIC), 1
        storeValue: (VARIABLE), 229, (STATIC), 100
        endIf: 
      endUpon: 
    upon: (FRAME_STEP)
      ifOperation: (IS_GREATER_OR_EQUAL), (VARIABLE), 25, (STATIC), 6
        ifOperation: (IS_GREATER_OR_EQUAL), (VARIABLE), 105, (STATIC), 150
          Unknown19: 23
          endIf: 
        endIf: 
      else: 
        ifOperation: (IS_GREATER_OR_EQUAL), (VARIABLE), 25, (STATIC), 3
          ifOperation: (IS_GREATER_OR_EQUAL), (VARIABLE), 105, (STATIC), 120
            Unknown19: 23
            endIf: 
          endIf: 
        else: 
          ifOperation: (IS_GREATER_OR_EQUAL), (VARIABLE), 105, (STATIC), 90
            Unknown19: 23
            endIf: 
          endElse: 
        endElse: 
      endUpon: 
    upon: 35
      Unknown41: 22
      storeValue: (VARIABLE), 229, (STATIC), 100
      Unknown40: 
      Unknown19: 23
      endUpon: 
    endUpon: 
  sprite: s32'null', 1
  sprite: s32'null', 1
  ifOperation: (IS_EQUAL), (VARIABLE), 115, (STATIC), 0
    Unknown41: 22
    storeValue: (VARIABLE), 229, (STATIC), 50
    Unknown40: 
    endIf: 
  ifOperation: (IS_EQUAL), (VARIABLE), 115, (STATIC), 1
    storeValue: (VARIABLE), 229, (STATIC), 100
    endIf: 
  setMarker: s32'loop'
  sprite: s32'null', 2
  ifOperation: (IS_EQUAL), (VARIABLE), 115, (STATIC), 0
    createObject2: s32'401EffDebuff', 133
    endIf: 
  Unknown3: 
  goToMarker: s32'loop'
  endState: 

startState: s32'LandSettingTypeNeedleObj'
  upon: (IMMEDIATE)
    Unknown244: 
    attackLevel: 2
    damage: 20
    Unknown1112: 0
    Unknown1110: 1
    hitPushbackX: 20
    Unknown2178: 
    numberOfHits: 2
    Unknown2189: 1
    Unknown2180: 1
    Unknown2181: 1
    Unknown2182: 1
    Unknown2183: 1
    Unknown58: 1
    ifOperation: (IS_GREATER_OR_EQUAL), (VARIABLE), 25, (STATIC), 3
      attackLevel: 3
      numberOfHits: 3
      endIf: 
    ifOperation: (IS_GREATER_OR_EQUAL), (VARIABLE), 25, (STATIC), 6
      attackLevel: 4
      numberOfHits: 4
      endIf: 
    upon: 45
      playCharacterSFX: s32'RVN_04_3'
      Unknown14: s32'koware'
      endUpon: 
    upon: (FRAME_STEP)
      ifOperation: (IS_EQUAL), (VARIABLE), 105, (STATIC), 10
        playCharacterSFX: s32'RVN_04_2'
        endIf: 
      ifOperation: (IS_EQUAL), (VARIABLE), 105, (STATIC), 20
        playCharacterSFX: s32'RVN_04_2'
        endIf: 
      ifOperation: (IS_EQUAL), (VARIABLE), 105, (STATIC), 30
        playCharacterSFX: s32'RVN_04_2'
        endIf: 
      ifOperation: (IS_EQUAL), (VARIABLE), 105, (STATIC), 40
        playCharacterSFX: s32'RVN_04_2'
        endIf: 
      ifOperation: (IS_EQUAL), (VARIABLE), 105, (STATIC), 50
        playCharacterSFX: s32'RVN_04_2'
        endIf: 
      ifOperation: (IS_EQUAL), (VARIABLE), 105, (STATIC), 60
        playCharacterSFX: s32'RVN_04_2'
        endIf: 
      ifOperation: (IS_EQUAL), (VARIABLE), 105, (STATIC), 70
        playCharacterSFX: s32'RVN_04_2'
        endIf: 
      ifOperation: (IS_EQUAL), (VARIABLE), 105, (STATIC), 115
        Unknown2176: 23
        endIf: 
      addVelocityX: 25
      addVelocityY: 50
      endUpon: 
    upon: 35
      Unknown2176: 23
      endUpon: 
    upon: 59
      Unknown19: 23
      endUpon: 
    Unknown1602: 1
    endUpon: 
  sprite: s32'null', 6
  playCharacterSFX: s32'RVN_04_1'
  Unknown3: 
  sprite: s32'rvn_SettingTypeNeedleObj', 20
  physicsXImpulse: 25000
  Unknown2197: 90
  physicsYImpulse: 6500
  Unknown2198: 99
  createObject2: s32'rvn403Eff', 100
  sprite: s32'rvn_SettingTypeNeedleObj', 24
  Unknown2198: 91
  setMarker: s32'loop'
  sprite: s32'rvn_SettingTypeNeedleObj', 5
  hit: 
  Unknown3: 
  goToMarker: s32'loop'
  setMarker: s32'koware'
  sprite: s32'null', 15
  createObject2: s32'rvn403EffEnd', 100
  Unknown32: s32'rvn403Eff'
  sprite: s32'null', 1
  Unknown19: 23
  endState: 

startState: s32'AirSettingTypeNeedleObj'
  upon: (IMMEDIATE)
    Unknown244: 
    attackLevel: 2
    damage: 20
    Unknown1112: 0
    Unknown1110: 1
    hitPushbackX: 20
    Unknown2178: 
    numberOfHits: 2
    Unknown2189: 1
    Unknown2180: 1
    Unknown2181: 1
    Unknown2182: 1
    Unknown2183: 1
    Unknown58: 1
    ifOperation: (IS_GREATER_OR_EQUAL), (VARIABLE), 25, (STATIC), 3
      attackLevel: 3
      numberOfHits: 3
      endIf: 
    ifOperation: (IS_GREATER_OR_EQUAL), (VARIABLE), 25, (STATIC), 6
      attackLevel: 4
      numberOfHits: 4
      endIf: 
    upon: 45
      playCharacterSFX: s32'RVN_04_3'
      Unknown14: s32'koware'
      endUpon: 
    upon: (FRAME_STEP)
      ifOperation: (IS_EQUAL), (VARIABLE), 105, (STATIC), 10
        playCharacterSFX: s32'RVN_04_2'
        endIf: 
      ifOperation: (IS_EQUAL), (VARIABLE), 105, (STATIC), 20
        playCharacterSFX: s32'RVN_04_2'
        endIf: 
      ifOperation: (IS_EQUAL), (VARIABLE), 105, (STATIC), 30
        playCharacterSFX: s32'RVN_04_2'
        endIf: 
      ifOperation: (IS_EQUAL), (VARIABLE), 105, (STATIC), 40
        playCharacterSFX: s32'RVN_04_2'
        endIf: 
      ifOperation: (IS_EQUAL), (VARIABLE), 105, (STATIC), 50
        playCharacterSFX: s32'RVN_04_2'
        endIf: 
      ifOperation: (IS_EQUAL), (VARIABLE), 105, (STATIC), 60
        playCharacterSFX: s32'RVN_04_2'
        endIf: 
      ifOperation: (IS_EQUAL), (VARIABLE), 105, (STATIC), 70
        playCharacterSFX: s32'RVN_04_2'
        endIf: 
      ifOperation: (IS_EQUAL), (VARIABLE), 105, (STATIC), 91
        Unknown2176: 23
        endIf: 
      endUpon: 
    upon: 35
      Unknown2176: 23
      endUpon: 
    upon: 59
      Unknown19: 23
      endUpon: 
    Unknown1602: 1
    setThrowRange: 100000
    endUpon: 
  sprite: s32'null', 6
  playCharacterSFX: s32'RVN_04_1'
  Unknown3: 
  physicsXImpulse: 30000
  physicsYImpulse: -30000
  Unknown2197: 94
  Unknown2198: 92
  createObject2: s32'rvn403EffAir', 100
  Unknown2267: 450
  sprite: s32'rvn_SettingTypeNeedleObj', 25
  setMarker: s32'loop'
  sprite: s32'rvn_SettingTypeNeedleObj', 6
  hit: 
  Unknown3: 
  goToMarker: s32'loop'
  setMarker: s32'koware'
  sprite: s32'null', 15
  createObject2: s32'rvn403EffEnd', 100
  Unknown32: s32'rvn403EffAir'
  sprite: s32'null', 1
  Unknown19: 23
  endState: 

startState: s32'AntiAirNeedleObj1'
  upon: (IMMEDIATE)
    Unknown244: 
    attackLevel: 1
    damage: 13
    setAttachOpponent: 1
    Unknown2178: 
    numberOfHits: 1
    Unknown2189: 1
    Unknown2180: 1
    Unknown2181: 1
    Unknown2182: 1
    Unknown2183: 1
    Unknown58: 1
    upon: 45
      Unknown448: s32'cmn_fd_end', 100
      Unknown19: 23
      endUpon: 
    upon: (FRAME_STEP)
      ifOperation: (IS_EQUAL), (VARIABLE), 105, (STATIC), 90
        Unknown2176: 23
        endIf: 
      endUpon: 
    Unknown1602: 1
    endUpon: 
  sprite: s32'null', 6
  sprite: s32'rvn_AntiAirNeedleObj', 2147483647
  Unknown450: s32'cmn_fd'
  Unknown2267: 200
  physicsXImpulse: 20000
  physicsYImpulse: 30000
  hit: 
  endState: 

startState: s32'AntiAirNeedleObj2'
  upon: (IMMEDIATE)
    Unknown244: 
    attackLevel: 1
    damage: 13
    setAttachOpponent: 1
    Unknown2178: 
    numberOfHits: 1
    Unknown2189: 1
    Unknown2180: 1
    Unknown2181: 1
    Unknown2182: 1
    Unknown2183: 1
    Unknown58: 1
    upon: 45
      Unknown448: s32'cmn_fd_end', 100
      Unknown19: 23
      endUpon: 
    upon: (FRAME_STEP)
      ifOperation: (IS_EQUAL), (VARIABLE), 105, (STATIC), 90
        Unknown2176: 23
        endIf: 
      endUpon: 
    Unknown1602: 1
    endUpon: 
  sprite: s32'null', 6
  sprite: s32'rvn_AntiAirNeedleObj', 10
  Unknown450: s32'cmn_fd'
  Unknown2267: 200
  sprite: s32'rvn_AntiAirNeedleObj', 2147483647
  physicsXImpulse: 20000
  physicsYImpulse: 30000
  hit: 
  endState: 

startState: s32'AntiAirNeedleObj3'
  upon: (IMMEDIATE)
    Unknown244: 
    attackLevel: 1
    damage: 13
    setAttachOpponent: 1
    Unknown2178: 
    numberOfHits: 1
    Unknown2189: 1
    Unknown2180: 1
    Unknown2181: 1
    Unknown2182: 1
    Unknown2183: 1
    Unknown58: 1
    upon: 45
      Unknown448: s32'cmn_fd_end', 100
      Unknown19: 23
      endUpon: 
    upon: (FRAME_STEP)
      ifOperation: (IS_EQUAL), (VARIABLE), 105, (STATIC), 90
        Unknown2176: 23
        endIf: 
      endUpon: 
    Unknown1602: 1
    endUpon: 
  sprite: s32'null', 6
  sprite: s32'rvn_AntiAirNeedleObj', 20
  Unknown450: s32'cmn_fd'
  Unknown2267: 200
  sprite: s32'rvn_AntiAirNeedleObj', 2147483647
  physicsXImpulse: 20000
  physicsYImpulse: 30000
  hit: 
  endState: 

startState: s32'Atk6D'
  sprite: s32'atk6D_00', 7
  upon: (ON_HIT_OR_BLOCK)
    Unknown457: 0
    endUpon: 
  Unknown456: 3
  Unknown457: 3
  endState: 

startState: s32'Craw_MatchWin'
  upon: (IMMEDIATE)
    Unknown294: 1
    endUpon: 
  sprite: s32'null', 1500
  createObject2: s32'Craw01', 100
  createObject2: s32'Craw02', 100
  createObject2: s32'Craw03', 100
  createObject2: s32'Craw04', 100
  endState: 

startState: s32'Craw01'
  upon: (IMMEDIATE)
    Unknown451: s32'craw', s32'rvn800cs_01'
    Unknown2021: 0
    endUpon: 
  sprite: s32'null', 1345
  endState: 

startState: s32'Craw02'
  upon: (IMMEDIATE)
    Unknown451: s32'craw', s32'rvn800cs_02'
    Unknown2021: 0
    endUpon: 
  sprite: s32'null', 1345
  endState: 

startState: s32'Craw03'
  upon: (IMMEDIATE)
    Unknown451: s32'craw', s32'rvn800cs_03'
    Unknown2021: 0
    endUpon: 
  sprite: s32'null', 1345
  endState: 

startState: s32'Craw04'
  upon: (IMMEDIATE)
    Unknown451: s32'craw', s32'rvn800cs_04'
    Unknown2021: 0
    endUpon: 
  sprite: s32'null', 1345
  endState: 

startState: s32'rvn032DashEff'
  upon: (IMMEDIATE)
    Unknown295: 1
    Unknown1769: 1
    Unknown466: 3
    Unknown450: s32'rvn_032dasheff00'
    setObjectSize: 1550
    Unknown94: 250000
    endUpon: 
  sprite: s32'null', 120
  endState: 

startState: s32'rvn032DashEff2'
  upon: (IMMEDIATE)
    Unknown295: 1
    Unknown1769: 1
    Unknown466: 3
    Unknown454: 2
    Unknown457: 2
    Unknown450: s32'rvn_032dasheff01'
    Unknown35: 23, s32'POS0'
    Unknown35: 24, s32'POS1'
    Unknown35: 25, s32'POS2'
    Unknown35: 26, s32'POS3'
    Unknown35: 27, s32'POS4'
    endUpon: 
  sprite: s32'null', 1
  Unknown94: 250000
  Unknown338: 0
  sprite: s32'null', 45
  Unknown338: 255
  setMarker: s32'POS0'
  sprite: s32'null', 30
  Unknown94: -60000
  setMarker: s32'POS1'
  sprite: s32'null', 2147483647
  Unknown94: -20000
  setMarker: s32'POS2'
  sprite: s32'null', 2147483647
  Unknown94: -80000
  setMarker: s32'POS3'
  sprite: s32'null', 2147483647
  Unknown94: -50000
  Unknown454: 0
  setMarker: s32'POS4'
  sprite: s32'null', 1
  Unknown94: -100000
  Unknown338: 0
  createObject2: s32'rvn032DashEffNokosi', 100
  endState: 

startState: s32'rvn032DashEffNokosi'
  upon: (IMMEDIATE)
    Unknown295: 1
    Unknown1769: 1
    Unknown466: 3
    Unknown450: s32'rvn_032dasheff02'
    endUpon: 
  sprite: s32'null', 60
  endState: 

startState: s32'DashPushCollisionObject'
  upon: (IMMEDIATE)
    Unknown454: 2
    Unknown457: 2
    Unknown456: 2
    endUpon: 
  sprite: s32'null', 7
  physicsXImpulse: 30000
  setNoCollision: 1
  sprite: s32'null', 1
  Unknown2006: 250000
  endState: 

startState: s32'rvn032DashEff2Test'
  upon: (IMMEDIATE)
    Unknown454: 2
    Unknown457: 2
    Unknown456: 2
    Unknown99: 250000
    endUpon: 
  sprite: s32'null', 5
  Unknown450: s32'rvn_032dasheff01Test'
  sprite: s32'null', 30
  Unknown454: 0
  Unknown457: 0
  Unknown456: 0
  endState: 

startState: s32'rvndashmodel2'
  upon: (IMMEDIATE)
    Unknown451: s32'Dash', s32''
    Unknown2021: 0
    Unknown454: 2
    Unknown457: 2
    Unknown456: 2
    upon: 36
      Unknown53: 23, 2, 7, 2, 2, 7
      Unknown111: -100
      endUpon: 
    Unknown94: 180000
    endUpon: 
  sprite: s32'null', 3
  createObject2: s32'rvn032DashEff2Test', 100
  sprite: s32'Dash000_00', 2
  sprite: s32'Dash000_01', 2
  Unknown94: 10000
  sprite: s32'Dash000_02', 2
  Unknown94: 40000
  sprite: s32'Dash000_03', 2
  Unknown94: 50000
  sprite: s32'Dash000_04', 2
  Unknown94: 50000
  sprite: s32'Dash000_05', 2
  Unknown94: 60000
  endState: 

startState: s32'rvn034Eff'
  upon: (IMMEDIATE)
    Unknown450: s32'rvn_043Eff_00'
    Unknown295: 1
    flipDirection: 
    endUpon: 
  sprite: s32'null', 60
  endState: 

startState: s32'rvn253Eff'
  upon: (IMMEDIATE)
    Unknown454: 2
    Unknown457: 2
    endUpon: 
  sprite: s32'null', 7
  Unknown450: s32'rvn_253Atk00'
  sprite: s32'null', 15
  endState: 

startState: s32'rvn253Eff1'
  upon: (IMMEDIATE)
    Unknown454: 2
    Unknown457: 2
    endUpon: 
  sprite: s32'null', 7
  Unknown450: s32'rvn_253Atk01'
  sprite: s32'null', 15
  endState: 

startState: s32'rvn253Eff2'
  upon: (IMMEDIATE)
    Unknown454: 2
    Unknown457: 2
    endUpon: 
  sprite: s32'null', 7
  Unknown450: s32'rvn_253Atk02'
  sprite: s32'null', 15
  endState: 

startState: s32'rvn401EffNokosi'
  upon: (IMMEDIATE)
    Unknown450: s32'rvn_401EffHane'
    Unknown295: 1
    Unknown1769: 1
    Unknown453: 2
    Unknown1700: 100000
    endUpon: 
  sprite: s32'null', 60
  endState: 

startState: s32'401EffDebuff'
  upon: (IMMEDIATE)
    Unknown454: 22
    Unknown450: s32'rvn_401EffDebuff'
    upon: (ON_HIT_OR_BLOCK)
      Unknown19: 23
      endIf: 
    endUpon: 
  sprite: s32'null', 20
  endState: 

startState: s32'rvn403Eff'
  upon: (IMMEDIATE)
    Unknown454: 2
    Unknown457: 2
    Unknown1700: 100000
    setObjectSize: 800
    Unknown1769: 1
    Unknown2267: 800
    Unknown165: 35000
    endUpon: 
  sprite: s32'null', 10
  Unknown450: s32'rvn_403startEff_00'
  Unknown347: 5
  Unknown353: 5
  Unknown359: 5
  setObjectSize: 200
  sprite: s32'null', 7
  setObjectSize: 300
  sprite: s32'null', 6
  setObjectSize: 400
  sprite: s32'null', 5
  setObjectSize: 450
  Unknown450: s32'rvn_403startEff_01'
  sprite: s32'null', 3
  setObjectSize: 500
  Unknown450: s32'rvn_403startEff_02'
  sprite: s32'null', 3
  setObjectSize: 550
  Unknown450: s32'rvn_403startEff_03'
  sprite: s32'null', 3
  setObjectSize: 600
  Unknown450: s32'rvn_403startEff_04'
  sprite: s32'null', 3
  setObjectSize: 650
  Unknown450: s32'rvn_403startEff_05'
  sprite: s32'null', 2
  setObjectSize: 700
  Unknown450: s32'rvn_403startEff_06'
  sprite: s32'null', 2
  setObjectSize: 750
  Unknown450: s32'rvn_403startEff_07'
  sprite: s32'null', 1
  Unknown450: s32'rvn_403EffJizoku'
  Unknown456: 2
  Unknown1769: 0
  setMarker: s32'Jizoku'
  sprite: s32'null', 2
  Unknown94: 12500
  Unknown448: s32'rvn_403EffJizokuHane', 100
  sprite: s32'null', 2
  Unknown94: -12500
  sprite: s32'null', 2
  Unknown94: 12500
  sprite: s32'null', 2
  Unknown94: -12500
  goToMarker: s32'Jizoku'
  endState: 

startState: s32'rvn403EffEnd'
  upon: (IMMEDIATE)
    Unknown1700: 100000
    Unknown165: 35000
    Unknown1769: 1
    endUpon: 
  sprite: s32'null', 60
  Unknown450: s32'rvn_403EffEnd'
  endState: 

startState: s32'rvn403EffAir'
  upon: (IMMEDIATE)
    Unknown454: 2
    Unknown457: 2
    Unknown1700: 100000
    Unknown1769: 1
    Unknown2267: 800
    Unknown165: 35000
    Unknown344: 100
    Unknown350: 100
    Unknown356: 100
    endUpon: 
  sprite: s32'null', 6
  Unknown450: s32'rvn_403startEff_00'
  Unknown347: 5
  Unknown353: 5
  Unknown359: 5
  setObjectSize: 400
  sprite: s32'null', 5
  setObjectSize: 450
  Unknown450: s32'rvn_403startEff_01'
  sprite: s32'null', 3
  setObjectSize: 500
  Unknown450: s32'rvn_403startEff_02'
  sprite: s32'null', 3
  setObjectSize: 550
  Unknown450: s32'rvn_403startEff_03'
  sprite: s32'null', 2
  setObjectSize: 600
  Unknown450: s32'rvn_403startEff_04'
  sprite: s32'null', 2
  setObjectSize: 650
  Unknown450: s32'rvn_403startEff_05'
  sprite: s32'null', 2
  setObjectSize: 700
  Unknown450: s32'rvn_403startEff_06'
  sprite: s32'null', 2
  setObjectSize: 750
  Unknown450: s32'rvn_403startEff_07'
  sprite: s32'null', 1
  setObjectSize: 800
  Unknown450: s32'rvn_403EffJizoku'
  Unknown456: 2
  Unknown344: 255
  Unknown350: 255
  Unknown356: 255
  Unknown1769: 0
  setMarker: s32'Jizoku'
  sprite: s32'null', 2
  Unknown94: 12500
  Unknown448: s32'rvn_403EffJizokuHane', 100
  sprite: s32'null', 2
  Unknown94: -12500
  sprite: s32'null', 2
  Unknown94: 12500
  sprite: s32'null', 2
  Unknown94: -12500
  goToMarker: s32'Jizoku'
  endState: 

startState: s32'rvn407EffATK1'
  upon: (IMMEDIATE)
    flipDirection: 
    Unknown457: 2
    Unknown456: 2
    Unknown454: 2
    endUpon: 
  sprite: s32'null', 30
  Unknown450: s32'rvn_407EffAtk01'
  endState: 

startState: s32'rvn407EffATK'
  upon: (IMMEDIATE)
    flipDirection: 
    Unknown457: 2
    Unknown456: 2
    Unknown454: 2
    endUpon: 
  sprite: s32'null', 30
  Unknown450: s32'rvn_407EffAtk02'
  endState: 

startState: s32'rvn407EffATK2'
  upon: (IMMEDIATE)
    flipDirection: 
    Unknown457: 2
    Unknown456: 2
    Unknown454: 2
    endUpon: 
  sprite: s32'null', 10
  Unknown450: s32'rvn_407EffAtk00'
  sprite: s32'null', 60
  Unknown457: 0
  Unknown456: 0
  Unknown454: 0
  Unknown1769: 1
  Unknown295: 1
  endState: 

startState: s32'rvn407EffATK2Air'
  upon: (IMMEDIATE)
    flipDirection: 
    Unknown457: 2
    Unknown456: 2
    Unknown454: 2
    endUpon: 
  sprite: s32'null', 10
  Unknown450: s32'rvn_407EffAtk00'
  sprite: s32'null', 60
  Unknown457: 0
  Unknown456: 0
  Unknown454: 0
  Unknown1769: 1
  Unknown295: 1
  endState: 

startState: s32'rvn409EffGareki'
  upon: (IMMEDIATE)
    Unknown178: 22
    Unknown98: 0
    Unknown295: 1
    Unknown450: s32'rvn_409Effgareki'
    setObjectSize: 1800
    endUpon: 
  sprite: s32'null', 15
  Unknown1769: 1
  sprite: s32'null', 20
  Unknown1769: 0
  createObject2: s32'rvn409EffGarekiSmoke', 100
  sprite: s32'null', 4
  Unknown99: -25000
  sprite: s32'null', 4
  Unknown99: -25000
  sprite: s32'null', 4
  Unknown99: -25000
  sprite: s32'null', 4
  Unknown99: -25000
  endState: 

startState: s32'rvn409EffGarekiSmoke'
  upon: (IMMEDIATE)
    Unknown295: 1
    Unknown450: s32'rvn_409Effsmok'
    endUpon: 
  sprite: s32'null', 60
  endState: 

startState: s32'rvn430Eff'
  upon: (IMMEDIATE)
    Unknown454: 2
    Unknown457: 2
    Unknown99: 180000
    Unknown94: 350000
    Unknown1700: 150000
    Unknown295: 1
    Unknown35: 23, s32'jizoku'
    Unknown35: 24, s32'End'
    endUpon: 
  sprite: s32'null', 2147483647
  Unknown450: s32'rvn_430EffStart'
  setMarker: s32'jizoku'
  sprite: s32'null', 1
  Unknown450: s32'rvn_430EffJizoku'
  setMarker: s32'jizokuLoop'
  sprite: s32'null', 2
  Unknown189: 50
  createObject2: s32'rvn430EffNokosi', 100
  sprite: s32'null', 2
  Unknown189: -50
  sprite: s32'null', 2
  Unknown189: 50
  sprite: s32'null', 2
  Unknown189: -50
  goToMarker: s32'jizokuLoop'
  setMarker: s32'End'
  sprite: s32'null', 60
  Unknown1771: s32'rvn430EffNokosi', 23
  Unknown454: 0
  Unknown457: 0
  Unknown450: s32'rvn_430EffEnd'
  endState: 

startState: s32'rvn430EffNokosi'
  upon: (IMMEDIATE)
    Unknown453: 2
    Unknown295: 1
    Unknown1769: 1
    Unknown450: s32'rvn_430EffNokosi'
    Unknown35: 23, s32'End'
    endUpon: 
  sprite: s32'null', 60
  setMarker: s32'End'
  sprite: s32'null', 10
  Unknown341: -26
  endState: 

startState: s32'rvn430EffSmoke'
  upon: (IMMEDIATE)
    Unknown457: 2
    Unknown295: 1
    Unknown1769: 1
    flipDirection: 
    setObjectSize: 570
    Unknown94: -250000
    endUpon: 
  sprite: s32'null', 5
  Unknown454: 2
  Unknown450: s32'rvn_430Eff_smoke'
  sprite: s32'null', 35
  Unknown454: 0
  sprite: s32'null', 60
  Unknown341: -4
  endState: 

startState: s32'rvn430EffSmoke2'
  upon: (IMMEDIATE)
    Unknown457: 2
    Unknown295: 1
    Unknown1769: 1
    flipDirection: 
    setObjectWidth: 570
    Unknown180: 570
    Unknown156: 620
    Unknown94: -50000
    endUpon: 
  sprite: s32'null', 5
  Unknown365: 20000, 20000
  Unknown454: 2
  Unknown450: s32'rvn_430Eff_smoke'
  sprite: s32'null', 35
  Unknown365: 20000, 20000
  Unknown454: 0
  sprite: s32'null', 60
  Unknown341: -4
  endState: 

startState: s32'rvn430EffRay'
  upon: (IMMEDIATE)
    Unknown454: 2
    Unknown457: 2
    Unknown455: 3
    Unknown295: 1
    Unknown1769: 1
    Unknown450: s32'rvn_430Ray'
    Unknown35: 23, s32'End'
    endUpon: 
  sprite: s32'null', 2147483647
  setMarker: s32'End'
  sprite: s32'null', 10
  Unknown341: -26
  endState: 

startState: s32'rvn432Eff00'
  upon: (IMMEDIATE)
    Unknown454: 2
    Unknown456: 2
    flipDirection: 
    Unknown450: s32'rvn_432Eff00'
    upon: 35
      Unknown19: 23
      endUpon: 
    endUpon: 
  sprite: s32'null', 60
  endState: 

startState: s32'rvn432EffLast'
  upon: (IMMEDIATE)
    Unknown454: 2
    Unknown456: 2
    flipDirection: 
    Unknown450: s32'rvn_432Eff01'
    Unknown99: 200000
    endUpon: 
  sprite: s32'null', 30
  sprite: s32'null', 30
  Unknown454: 0
  endState: 

startState: s32'rvn432EffBake'
  upon: (IMMEDIATE)
    Unknown454: 2
    Unknown457: 2
    Unknown456: 2
    flipDirection: 
    endUpon: 
  setMarker: s32'Loop'
  sprite: s32'null', 2
  Unknown450: s32'rvn_432Eff_bake00'
  sprite: s32'null', 2
  Unknown450: s32'rvn_432Eff_bake01'
  sprite: s32'null', 2
  Unknown450: s32'rvn_432Eff_bake02'
  goToMarker: s32'Loop'
  endState: 

startState: s32'rvn432EffBake2'
  upon: (IMMEDIATE)
    Unknown454: 2
    Unknown457: 2
    Unknown456: 2
    flipDirection: 
    endUpon: 
  setMarker: s32'Loop'
  sprite: s32'null', 2
  Unknown450: s32'rvn_432Eff_bake03'
  sprite: s32'null', 2
  Unknown450: s32'rvn_432Eff_bake04'
  sprite: s32'null', 2
  Unknown450: s32'rvn_432Eff_bake05'
  goToMarker: s32'Loop'
  endState: 

startState: s32'rvn432EffHit'
  upon: (IMMEDIATE)
    Unknown1769: 1
    Unknown295: 1
    setObjectSize: 800
    Unknown194: -300, 0
    Unknown102: -100000, 100000
    Unknown103: 0, 200000
    Unknown1703: -50000, 50000
    Unknown169: -2500, 2500
    endUpon: 
  sprite: s32'null', 60
  Unknown450: s32'rvn_432Eff_HitEff'
  endState: 

startState: s32'rvn432EffHit2'
  upon: (IMMEDIATE)
    Unknown1769: 1
    Unknown295: 1
    setObjectSize: 1400
    Unknown94: 150000
    endUpon: 
  sprite: s32'null', 60
  Unknown450: s32'rvn_432Eff_HitEff2'
  endState: 

startState: s32'rvn432Usugura'
  upon: (IMMEDIATE)
    Unknown457: 2
    endUpon: 
  sprite: s32'null', 2147483647
  Unknown450: s32'rvn_433Usugura'
  endState: 

startState: s32'rvn432Kira'
  upon: (IMMEDIATE)
    Unknown457: 2
    endUpon: 
  sprite: s32'null', 2147483647
  Unknown450: s32'rvn_433ScrnAnim'
  endState: 

startState: s32'IKface'
  upon: (IMMEDIATE)
    Unknown451: s32'ikface', s32'ikface01'
    Unknown2021: 0
    endUpon: 
  sprite: s32'null', 600
  endState: 

startState: s32'rvn451AuraJizoku'
  upon: (IMMEDIATE)
    physicsXImpulse: 1000
    Unknown338: 0
    Unknown450: s32'rvn_451Eff_AuraJizoku'
    endUpon: 
  sprite: s32'null', 200
  Unknown341: 3
  endState: 

startState: s32'rvn451Aura'
  upon: (IMMEDIATE)
    endUpon: 
  setMarker: s32'Loop'
  sprite: s32'null', 15
  Unknown2246: s32'footL', 0
  Unknown449: s32'rvn_451Eff_Aura2', 100
  Unknown2246: s32'footR', 0
  Unknown449: s32'rvn_451Eff_Aura2', 100
  goToMarker: s32'Loop'
  endState: 

startState: s32'rvn451Aura2'
  upon: (IMMEDIATE)
    endUpon: 
  setMarker: s32'Loop'
  sprite: s32'null', 25
  Unknown2246: s32'calfL', 0
  Unknown449: s32'rvn_451Eff_Aura', 100
  Unknown2246: s32'calfR', 0
  Unknown449: s32'rvn_451Eff_Aura', 100
  goToMarker: s32'Loop'
  endState: 

startState: s32'rvn451Aura3'
  upon: (IMMEDIATE)
    endUpon: 
  setMarker: s32'Loop'
  sprite: s32'null', 25
  Unknown2246: s32'pelvis', 0
  Unknown449: s32'rvn_451Eff_Aura', 100
  goToMarker: s32'Loop'
  endState: 

startState: s32'rvn451Aura4'
  upon: (IMMEDIATE)
    endUpon: 
  setMarker: s32'Loop'
  sprite: s32'null', 25
  Unknown2246: s32'chest', 0
  Unknown449: s32'rvn_451Eff_Aura', 100
  goToMarker: s32'Loop'
  endState: 

startState: s32'rvn451Aura5'
  upon: (IMMEDIATE)
    endUpon: 
  setMarker: s32'Loop'
  sprite: s32'null', 25
  Unknown2246: s32'chest', 0
  Unknown449: s32'rvn_451Eff_Aura', 100
  goToMarker: s32'Loop'
  endState: 

startState: s32'rvn451Aura6'
  upon: (IMMEDIATE)
    endUpon: 
  setMarker: s32'Loop'
  sprite: s32'null', 25
  Unknown2246: s32'handR', 0
  Unknown449: s32'rvn_451Eff_Aura', 100
  Unknown2246: s32'handL', 0
  Unknown449: s32'rvn_451Eff_Aura', 100
  goToMarker: s32'Loop'
  endState: 

startState: s32'rvn451Aura7'
  upon: (IMMEDIATE)
    endUpon: 
  setMarker: s32'Loop'
  sprite: s32'null', 25
  Unknown2246: s32'head', 0
  Unknown449: s32'rvn_451Eff_Aura', 100
  goToMarker: s32'Loop'
  endState: 

startState: s32'rvn451Tanka'
  upon: (IMMEDIATE)
    Unknown450: s32'rvn_451Eff_tanka00'
    endUpon: 
  sprite: s32'null', 60
  endState: 

startState: s32'rvn451HandAura'
  upon: (IMMEDIATE)
    physicsXImpulse: 1000
    Unknown450: s32'rvn_451Eff_AuraJizoku2'
    endUpon: 
  sprite: s32'null', 2147483647
  endState: 

startState: s32'rvn451AuraJizoku2'
  upon: (IMMEDIATE)
    Unknown450: s32'rvn_451Eff_AuraJizoku'
    setObjectSize: 900
    endUpon: 
  sprite: s32'null', 2147483647
  endState: 

startState: s32'rvn451Eye'
  upon: (IMMEDIATE)
    flipDirection: 
    Unknown450: s32'rvn_451Eff_eyeray'
    endUpon: 
  sprite: s32'null', 120
  Unknown338: 0
  Unknown341: 2
  sprite: s32'null', 2147483647
  Unknown341: 0
  endState: 

startState: s32'rvn451HibasiraJizoku'
  upon: (IMMEDIATE)
    Unknown450: s32'rvn_451Eff_HibasiraJizoku'
    setObjectSize: 3200
    Unknown35: 23, s32'HiroGari'
    endUpon: 
  setMarker: s32'Loop'
  sprite: s32'null', 2
  Unknown149: -120
  Unknown181: -120
  sprite: s32'null', 2
  Unknown149: 120
  Unknown181: 120
  goToMarker: s32'Loop'
  setMarker: s32'HiroGari'
  sprite: s32'null', 2147483647
  Unknown450: s32'rvn_451Eff_HibasiraEnd'
  Unknown191: 2500
  Unknown3: 
  endState: 

startState: s32'rvn451hai'
  upon: (IMMEDIATE)
    Unknown450: s32'rvn_451Eff_hai'
    Unknown35: 23, s32'hai2'
    endUpon: 
  sprite: s32'null', 2147483647
  setMarker: s32'hai2'
  sprite: s32'null', 2147483647
  Unknown450: s32'rvn_451Eff_hai2'
  endState: 

startState: s32'rvn451hai2'
  upon: (IMMEDIATE)
    Unknown450: s32'rvn_451Eff_sandshock'
    setObjectSize: 700
    endUpon: 
  sprite: s32'null', 300
  endState: 

startState: s32'rvn451BG'
  upon: (IMMEDIATE)
    Unknown450: s32'rvn_451Eff_BG'
    Unknown35: 23, s32'Scale'
    Unknown35: 24, s32'Scale2'
    endUpon: 
  sprite: s32'null', 2147483647
  setMarker: s32'Scale'
  sprite: s32'null', 2147483647
  Unknown189: 4000
  setMarker: s32'Scale2'
  sprite: s32'null', 2147483647
  Unknown189: -4000
  endState: 

startState: s32'rvn700BG'
  upon: (IMMEDIATE)
    Unknown457: 2
    Unknown450: s32'rvn_700_bg00'
    flipDirection: 
    endUpon: 
  sprite: s32'null', 2147483647
  endState: 

startState: s32'rvn700_feather'
  upon: (IMMEDIATE)
    Unknown450: s32'rvn_700_feather'
    endUpon: 
  sprite: s32'null', 2147483647
  endState: 

startState: s32'rvn800BG'
  upon: (IMMEDIATE)
    Unknown457: 2
    Unknown450: s32'rvn_800_hanefade'
    flipDirection: 
    endUpon: 
  sprite: s32'null', 2147483647
  endState: 

startState: s32'cs800_Craw01'
  upon: (IMMEDIATE)
    Unknown451: s32'Craw01', s32'rvn800cs_craw01'
    Unknown2021: 0
    endUpon: 
  sprite: s32'null', 2147483647
  endState: 

startState: s32'cs800_Craw02'
  upon: (IMMEDIATE)
    Unknown451: s32'Craw02', s32'rvn800cs_craw02'
    Unknown2021: 0
    endUpon: 
  sprite: s32'null', 2147483647
  endState: 

startState: s32'cs800_Craw03'
  upon: (IMMEDIATE)
    Unknown451: s32'Craw03', s32'rvn800cs_craw03'
    Unknown2021: 0
    endUpon: 
  sprite: s32'null', 2147483647
  endState: 

startState: s32'cs800_Craw04'
  upon: (IMMEDIATE)
    Unknown451: s32'Craw04', s32'rvn800cs_craw04'
    Unknown2021: 0
    endUpon: 
  sprite: s32'null', 2147483647
  endState: 

startState: s32'200bake'
  upon: (IMMEDIATE)
    Unknown457: 2
    Unknown456: 2
    Unknown454: 2
    endUpon: 
  sprite: s32'null', 20
  Unknown450: s32'rvn_200Atk'
  endState: 

startState: s32'202bake1'
  upon: (IMMEDIATE)
    Unknown457: 2
    Unknown456: 2
    Unknown454: 2
    endUpon: 
  sprite: s32'null', 20
  Unknown450: s32'rvn_202Atk00'
  endState: 

startState: s32'202bake2'
  upon: (IMMEDIATE)
    Unknown457: 2
    Unknown456: 2
    Unknown454: 2
    endUpon: 
  sprite: s32'null', 20
  Unknown450: s32'rvn_202Atk01'
  endState: 

startState: s32'203bake'
  upon: (IMMEDIATE)
    Unknown457: 2
    Unknown456: 2
    Unknown454: 2
    endUpon: 
  sprite: s32'null', 20
  Unknown450: s32'rvn_203Atk'
  endState: 

startState: s32'204bake'
  upon: (IMMEDIATE)
    Unknown457: 2
    Unknown456: 2
    Unknown454: 2
    endUpon: 
  sprite: s32'null', 20
  Unknown450: s32'rvn_204Atk'
  endState: 

startState: s32'205bake'
  upon: (IMMEDIATE)
    Unknown457: 2
    Unknown456: 2
    Unknown454: 2
    endUpon: 
  sprite: s32'null', 15
  Unknown450: s32'rvn_205Atk00'
  endState: 

startState: s32'210bake'
  upon: (IMMEDIATE)
    Unknown457: 2
    Unknown456: 2
    Unknown454: 2
    endUpon: 
  sprite: s32'null', 3
  Unknown450: s32'rvn_210Atk00'
  sprite: s32'null', 60
  Unknown450: s32'rvn_210Atk01'
  Unknown338: 127
  Unknown454: 0
  Unknown457: 0
  Unknown456: 0
  Unknown295: 1
  Unknown1769: 1
  endState: 

startState: s32'213bake'
  upon: (IMMEDIATE)
    Unknown457: 2
    Unknown456: 2
    Unknown454: 2
    endUpon: 
  sprite: s32'null', 20
  Unknown450: s32'rvn_213Atk'
  endState: 

startState: s32'213atk'
  upon: (IMMEDIATE)
    Unknown457: 2
    Unknown456: 2
    Unknown94: 270000
    Unknown99: 110000
    setObjectSize: 1300
    endUpon: 
  sprite: s32'null', 5
  Unknown450: s32'rvn_213Atk_col'
  sprite: s32'null', 60
  Unknown457: 0
  Unknown456: 0
  Unknown295: 1
  Unknown1769: 1
  endState: 

startState: s32'215bake1'
  upon: (IMMEDIATE)
    Unknown457: 2
    Unknown456: 2
    Unknown454: 2
    endUpon: 
  sprite: s32'null', 15
  Unknown450: s32'rvn_215Atk00'
  endState: 

startState: s32'215bake2'
  upon: (IMMEDIATE)
    Unknown457: 2
    Unknown456: 2
    Unknown454: 2
    endUpon: 
  sprite: s32'null', 15
  Unknown450: s32'rvn_215Atk01'
  endState: 

startState: s32'230bake'
  upon: (IMMEDIATE)
    Unknown457: 2
    Unknown456: 2
    Unknown454: 2
    endUpon: 
  sprite: s32'null', 15
  Unknown450: s32'rvn_230Atk'
  endState: 

startState: s32'232bake'
  upon: (IMMEDIATE)
    Unknown457: 2
    Unknown456: 2
    Unknown454: 2
    endUpon: 
  sprite: s32'null', 15
  Unknown450: s32'rvn_232Atk'
  endState: 

startState: s32'233bake'
  upon: (IMMEDIATE)
    Unknown457: 2
    Unknown456: 2
    Unknown454: 2
    Unknown99: 22500
    endUpon: 
  sprite: s32'null', 2
  Unknown450: s32'rvn_233Atk00'
  sprite: s32'null', 2
  Unknown450: s32'rvn_233Atk01'
  sprite: s32'null', 3
  Unknown450: s32'rvn_233Atk02'
  sprite: s32'null', 3
  Unknown450: s32'rvn_233Atk03'
  sprite: s32'null', 60
  Unknown450: s32'rvn_233Atk04'
  Unknown457: 0
  Unknown456: 0
  Unknown454: 0
  Unknown341: -10
  endState: 

startState: s32'250bake'
  upon: (IMMEDIATE)
    Unknown457: 2
    Unknown456: 2
    Unknown454: 2
    endUpon: 
  sprite: s32'null', 20
  Unknown450: s32'rvn_250Atk'
  endState: 

startState: s32'252bake'
  upon: (IMMEDIATE)
    Unknown457: 2
    Unknown456: 2
    Unknown454: 2
    endUpon: 
  sprite: s32'null', 20
  Unknown450: s32'rvn_252Atk00'
  endState: 

startState: s32'254bake'
  upon: (IMMEDIATE)
    Unknown457: 2
    Unknown456: 2
    Unknown454: 2
    endUpon: 
  sprite: s32'null', 20
  Unknown450: s32'rvn_254Atk00'
  endState: 

startState: s32'320Eff'
  upon: (IMMEDIATE)
    Unknown457: 2
    Unknown456: 2
    Unknown454: 2
    Unknown450: s32'rvn_320Eff'
    endUpon: 
  sprite: s32'null', 30
  Unknown365: 15000, 15000
  endState: 

startState: s32'320Eff_hit'
  upon: (IMMEDIATE)
    Unknown454: 2
    Unknown450: s32'rvn_320Eff_hit'
    endUpon: 
  sprite: s32'null', 60
  Unknown365: 20000, 20000
  endState: 

startState: s32'360bake'
  upon: (IMMEDIATE)
    Unknown457: 2
    Unknown456: 2
    Unknown454: 2
    endUpon: 
  sprite: s32'null', 20
  Unknown450: s32'rvn_neoblitz_atk'
  endState: 

startState: s32'Zanhit_oku'
  upon: (IMMEDIATE)
    Unknown450: s32'cmn_slash_s_oku'
    endUpon: 
  sprite: s32'null', 55
  endState: 

startState: s32'BG_win'
  upon: (IMMEDIATE)
    Unknown457: 3
    Unknown450: s32'rvn_800_bg00'
    endUpon: 
  sprite: s32'null', 1000
  endState: 

startState: s32'FinishCamera_RevengeAttack'
  upon: (IMMEDIATE)
    Unknown294: 1
    Unknown1769: 1
    Unknown2065: 
    Unknown2050: 
    endUpon: 
  sprite: s32'null', 180
  Unknown2047: 23, -115127, 189036, 65367, 295, 5163, 89, 90, 180, 0, 20, 0, 2, 2
  endState: 

startState: s32'ACEvtRVN_8A'
  upon: (IMMEDIATE)
    Unknown2114: -16777216, -16777216, 1
    Unknown2107: '0x4576656E745374616E640000000000000000000000000000000000000000000000000000'
    Unknown2107: '0x4576656E7452564E3038415F303100000000000000000000000000000000000001000000'
    endUpon: 
  sprite: s32'null', 1
  Unknown2123: s32'BGM_HEIJI2'
  Unknown2123: s32'BGM_HEIJI006'
  Unknown2123: s32'BGM_Kincho2'
  Unknown2123: s32'BGM_Fear'
  Unknown2122: 
  sprite: s32'null', 120
  Unknown2114: -16777216, 0, 30
  Unknown2120: '0x4845494A4932000000000000000000000000000000000000000000000000000000000000'
  Unknown2115: 50, 0
  sprite: s32'null', 2147483647
  Unknown2106: '0x4143325F52564E5F4238415F30303000000000000000000000000000000000002D000000'
  sprite: s32'null', 2147483647
  Unknown2106: '0x4143325F52564E5F4238415F30303100000000000000000000000000000000002D000000'
  sprite: s32'null', 2147483647
  Unknown2106: '0x4143325F52564E5F4238415F30303200000000000000000000000000000000002D000000'
  sprite: s32'null', 2147483647
  Unknown2106: '0x4143325F52564E5F4238415F30303300000000000000000000000000000000001E000000'
  sprite: s32'null', 2147483647
  Unknown2106: '0x4143325F52564E5F4238415F30303400000000000000000000000000000000002D000000'
  sprite: s32'null', 2147483647
  Unknown2106: '0x4143325F52564E5F4238415F30303500000000000000000000000000000000005A000000'
  sprite: s32'null', 2147483647
  Unknown2106: '0x4143325F52564E5F4238415F30303600000000000000000000000000000000003C000000'
  Unknown2107: '0x4576656E7452564E3038415F303200000000000000000000000000000000000001000000'
  sprite: s32'null', 2147483647
  Unknown2106: '0x4143325F52564E5F4238415F30303700000000000000000000000000000000002D000000'
  sprite: s32'null', 2147483647
  Unknown2106: '0x4143325F52564E5F4238415F30303800000000000000000000000000000000002D000000'
  sprite: s32'null', 2147483647
  Unknown2106: '0x4143325F52564E5F4238415F30303900000000000000000000000000000000002D000000'
  sprite: s32'null', 2147483647
  Unknown2106: '0x4143325F52564E5F4238415F30313000000000000000000000000000000000003C000000'
  sprite: s32'null', 2147483647
  Unknown2106: '0x4143325F52564E5F4238415F30313100000000000000000000000000000000001E000000'
  sprite: s32'null', 2147483647
  Unknown2106: '0x4143325F52564E5F4238415F30313200000000000000000000000000000000002D000000'
  Unknown2107: '0x4576656E7452564E3038415F303300000000000000000000000000000000000001000000'
  sprite: s32'null', 1
  Unknown2108: 
  endState: 

startState: s32'ACEvtRVN_8B'
  upon: (IMMEDIATE)
    Unknown2114: -16777216, -16777216, 1
    Unknown2107: '0x4576656E7452564E3038425F303100000000000000000000000000000000000000000000'
    Unknown2107: '0x4576656E7452564E3038425F303100000000000000000000000000000000000001000000'
    endUpon: 
  sprite: s32'null', 1
  Unknown2114: -16777216, 0, 30
  Unknown2120: '0x4845494A4930303600000000000000000000000000000000000000000000000000000000'
  Unknown2115: 50, 0
  sprite: s32'null', 2147483647
  Unknown2106: '0x4143325F52564E5F4238425F30303000000000000000000000000000000000002D000000'
  sprite: s32'null', 2147483647
  Unknown2106: '0x4143325F52564E5F4238425F30303100000000000000000000000000000000001E000000'
  Unknown2107: '0x4576656E7452564E3038425F303200000000000000000000000000000000000001000000'
  sprite: s32'null', 2147483647
  Unknown2106: '0x4143325F52564E5F4238425F30303200000000000000000000000000000000002D000000'
  sprite: s32'null', 2147483647
  Unknown2106: '0x4143325F52564E5F4238425F30303300000000000000000000000000000000002D000000'
  Unknown2107: '0x4576656E7452564E3038425F303300000000000000000000000000000000000001000000'
  sprite: s32'null', 2147483647
  Unknown2106: '0x4143325F52564E5F4238425F30303400000000000000000000000000000000003C000000'
  sprite: s32'null', 2147483647
  Unknown2106: '0x4143325F52564E5F4238425F30303500000000000000000000000000000000003C000000'
  Unknown2107: '0x4576656E7452564E3038425F303200000000000000000000000000000000000000000000'
  sprite: s32'null', 2147483647
  Unknown2106: '0x4143325F52564E5F4238425F30303600000000000000000000000000000000003C000000'
  Unknown2115: 0, 60
  sprite: s32'null', 2147483647
  Unknown2106: '0x4143325F52564E5F4238425F30303700000000000000000000000000000000005A000000'
  sprite: s32'null', 2147483647
  Unknown2106: '0x4143325F52564E5F4238425F30303800000000000000000000000000000000002D000000'
  Unknown2107: '0x4576656E7452564E3038425F303400000000000000000000000000000000000001000000'
  Unknown2120: '0x4B696E63686F320000000000000000000000000000000000000000000000000000000000'
  Unknown2115: 100, 0
  sprite: s32'null', 2147483647
  Unknown2106: '0x4143325F52564E5F4238425F30303900000000000000000000000000000000001E000000'
  Unknown2107: '0x4576656E7452564E3038425F303300000000000000000000000000000000000000000000'
  sprite: s32'null', 2147483647
  Unknown2106: '0x4143325F52564E5F4238425F30313000000000000000000000000000000000002D000000'
  Unknown2107: '0x4576656E7452564E3038425F303500000000000000000000000000000000000001000000'
  sprite: s32'null', 2147483647
  Unknown2106: '0x4143325F52564E5F4238425F30313100000000000000000000000000000000001E000000'
  Unknown2107: '0x4576656E7452564E3038425F303600000000000000000000000000000000000001000000'
  sprite: s32'null', 2147483647
  Unknown2106: '0x4143325F52564E5F4238425F303132000000000000000000000000000000000069000000'
  Unknown1766: 22, 23
  Unknown2115: 0, 30
  sprite: s32'null', 2147483647
  Unknown2106: '0x4143325F52564E5F4238425F30313400000000000000000000000000000000005A000000'
  sprite: s32'null', 30
  Unknown2107: '0x4576656E7452564E3038425F303700000000000000000000000000000000000001000000'
  sprite: s32'null', 2147483647
  Unknown2106: '0x4143325F52564E5F4238425F30313600000000000000000000000000000000003C000000'
  sprite: s32'null', 120
  Unknown2106: '0x4143325F52564E5F4238425F30313700000000000000000000000000000000003C000000'
  sprite: s32'null', 1
  Unknown2108: 
  endState: 

