beginState: s32'obj_ven_ballend_lv2'
  upon: (IMMEDIATE)
    linkObjPositionTo: (PARENT)
    endUpon: 
  sprite: s32'null', 20
  linkParticleEx: s32'ven_ballend_lv2'
  endState: 

beginState: s32'obj_ven_ballend_lv3'
  upon: (IMMEDIATE)
    linkObjPositionTo: (PARENT)
    endUpon: 
  sprite: s32'null', 20
  linkParticleEx: s32'ven_ballend_lv3'
  endState: 

beginState: s32'obj_ven_ballend_lv4'
  upon: (IMMEDIATE)
    linkObjPositionTo: (PARENT)
    endUpon: 
  sprite: s32'null', 20
  linkParticleEx: s32'ven_ballend_lv4'
  endState: 

beginState: s32'Airdust_bake'
  upon: (IMMEDIATE)
    linkObjPositionTo: (PLAYER)
    Unknown456: (PLAYER)
    Unknown457: (PLAYER)
    endUpon: 
  sprite: s32'null', 20
  linkParticleEx: s32'ven_airdust_bake'
  endState: 

beginState: s32'Dhm01'
  upon: (IMMEDIATE)
    linkObjPositionTo: (PLAYER)
    Unknown456: (PLAYER)
    Unknown457: (PLAYER)
    endUpon: 
  sprite: s32'null', 20
  linkParticleEx: s32'ven_cue_zanzo1'
  endState: 

beginState: s32'Dhm02'
  upon: (IMMEDIATE)
    linkObjPositionTo: (PLAYER)
    Unknown456: (PLAYER)
    Unknown457: (PLAYER)
    endUpon: 
  sprite: s32'null', 20
  linkParticleEx: s32'ven_cue_zanzo2'
  endState: 

beginState: s32'Dhm03'
  upon: (IMMEDIATE)
    linkObjPositionTo: (PLAYER)
    Unknown456: (PLAYER)
    Unknown457: (PLAYER)
    endUpon: 
  sprite: s32'null', 20
  linkParticleEx: s32'ven_cue_zanzo3'
  endState: 

beginState: s32'Warpmodel1'
  upon: (IMMEDIATE)
    Unknown456: (PLAYER)
    Unknown457: (PLAYER)
    endUpon: 
  sprite: s32'null', 20
  linkParticleEx: s32'ven_warp01'
  endState: 

beginState: s32'Warpmodel2'
  upon: (IMMEDIATE)
    linkObjPositionTo: (PLAYER)
    Unknown456: (PLAYER)
    Unknown457: (PLAYER)
    endUpon: 
  sprite: s32'null', 20
  linkParticleEx: s32'ven_warp02'
  endState: 

beginState: s32'Debious_AttackBall'
  upon: (IMMEDIATE)
    Unknown244: 
    attackLevel: 0
    ifOperation: (IS_EQUAL), Mem(115), Val(1)
      attackLevel: 1
      endIf: 
    ifOperation: (IS_EQUAL), Mem(115), Val(2)
      attackLevel: 2
      endIf: 
    ifOperation: (IS_EQUAL), Mem(115), Val(3)
      attackLevel: 3
      endIf: 
    Unknown1028: 3
    Unknown1110: 1
    isAirUnblockable: 1
    groundHitEffect: (AIR_FACE_UP)
    damage: 25
    untechableTime: 30
    hitAirPushbackX: 2000
    hitAirPushbackY: 20000
    counterHitUntechableTime: 46
    groundCounterHitEffect: (AIR_STRONG)
    counterHitWallBounceCount: 1
    counterhitAirPushbackX: 40000
    counterhitAirPushbackY: 20000
    endUpon: 
  sprite: s32'vee_dcurve_atk_rx', 2
  linkParticleEx: s32'ven_dubious_atk'
  setObjectSize: 100
  Unknown191: 120
  Unknown2267: 1300
  sprite: s32'vee_dcurve_atk_rx', 2
  sprite: s32'vee_dcurve_atk_rx', 2
  Unknown191: 40
  hit: 
  sprite: s32'vee_dcurve_atk_rx', 2
  sprite: s32'vee_dcurve_atk_rx', 2
  sprite: s32'vee_dcurve_atk_rx', 2
  sprite: s32'vee_dcurve_atk_rx', 50
  Unknown191: 0
  recoveryState: 
  endState: 

beginState: s32'ven_winhandball_screen'
  upon: (IMMEDIATE)
    Unknown457: (PLAYER)
    linkObjPositionTo: (PLAYER)
    Unknown456: (PLAYER)
    linkParticleEx: s32'ven_winhandball_screen'
    endUpon: 
  sprite: s32'null', 1000
  endState: 

beginState: s32'Debious_hatudo'
  upon: (IMMEDIATE)
    linkObjPositionTo: (PLAYER)
    Unknown456: (PLAYER)
    Unknown457: (PLAYER)
    endUpon: 
  sprite: s32'null', 50
  linkParticleEx: s32'ven_dubious_hatudo'
  endState: 

startSubroutine: s32'BallReset'
  storeValue: Mem(52), Val(0)
  storeValue: Mem(47), Val(0)
  storeValue: Mem(45), Val(0)
  storeValue: Mem(46), Val(1)
  storeValue: Mem(50), Val(1)
  storeValue: Mem(54), Val(0)
  clearUpon: (HIT_OR_BLOCK)
  linkObjPositionTo: (NULL)
  callCmnEfFunc: s32'BallScaleUpdate'
  Unknown1058: 1
  endSubroutine: 

startSubroutine: s32'BallScaleUpdate'
  Unknown191: 0
  setObjectSize: 1000
  ifOperation: (IS_EQUAL), Mem(69), Val(5)
    ifOperation: (IS_EQUAL), Mem(70), Val(0)
      setObjectSize: 2000
      endIf: 
    ifOperation: (IS_EQUAL), Mem(70), Val(1)
      setObjectSize: 2400
      endIf: 
    ifOperation: (IS_EQUAL), Mem(70), Val(2)
      setObjectSize: 2800
      endIf: 
    ifOperation: (IS_EQUAL), Mem(70), Val(3)
      setObjectSize: 3200
      endIf: 
    ifOperation: (IS_EQUAL), Mem(70), Val(4)
      setObjectSize: 3600
      endIf: 
    ifOperation: (IS_GREATER_OR_EQUAL), Mem(70), Val(5)
      setObjectSize: 4000
      endIf: 
    endIf: 
  endSubroutine: 

beginState: s32'Ball'
  upon: (IMMEDIATE)
    storeValue: Mem(69), Val(1)
    Unknown244: 
    linkParticleEx: s32'ven_ball'
    attackLevel: 2
    setAttachOpponent: 1
    riscMinus: 7
    Unknown1137: 32
    setAttachOpponent: 1
    Unknown1058: 1
    Unknown1165: s32'Ball_Normal'
    if: Mem(116)
      upon: 9
        riscPlus: 10
        clearUpon: 9
        upon: 9
          clearUpon: 9
          riscPlus: 2
          endUpon: 
        endUpon: 
      endIf: 
    callSubroutine: s32'VeBallFlagSet', 0, 2, 0, 0, 0, 0, 0, 0
    upon: (HIT_OR_GUARD)
      if: Mem(47)
        Unknown2176: 23
        endIf: 
      endUpon: 
    setThrowRange: 0
    numberOfHits: 1
    Unknown2180: 1
    Unknown2181: 1
    Unknown2182: 1
    Unknown2183: 1
    Unknown2187: 1
    Unknown2188: 1
    upon: (ON_DESTROY)
      deactivateObj: (SELF)
      ifOperation: (IS_EQUAL), Mem(69), Val(1)
        Unknown448: s32'ven_ballend', 100
        endIf: 
      ifOperation: (IS_EQUAL), Mem(69), Val(2)
        Unknown448: s32'ven_ballend_lv2', 100
        endIf: 
      ifOperation: (IS_EQUAL), Mem(69), Val(3)
        Unknown448: s32'ven_ballend_lv3', 100
        endIf: 
      ifOperation: (IS_EQUAL), Mem(69), Val(4)
        Unknown448: s32'ven_ballend_lv4', 100
        endIf: 
      ifOperation: (IS_EQUAL), Mem(69), Val(5)
        Unknown2242: 0, 180
        Unknown449: s32'ven_ballend_lv4', 100
        endIf: 
      endUpon: 
    storeValue: Mem(47), Val(480)
    storeValue: Mem(45), Val(1)
    upon: 25
      storeValue: Mem(47), Val(600)
      storeValue: Mem(48), Val(2)
      endUpon: 
    upon: 26
      storeValue: Mem(47), Val(720)
      storeValue: Mem(48), Val(3)
      endUpon: 
    upon: 27
      storeValue: Mem(47), Val(840)
      storeValue: Mem(48), Val(4)
      endUpon: 
    upon: 28
      storeValue: Mem(47), Val(960)
      storeValue: Mem(48), Val(5)
      endUpon: 
    upon: 29
      Unknown14: s32'Homing'
      endUpon: 
    ifOperation: (IS_EQUAL), Mem(115), Val(1)
      callSubroutine: s32'VeBallFlagAdd', 0, 128, 0, 0, 0, 0, 0, 0
      storeValue: Mem(45), Val(0)
      resetVelocity: 1
      storeValue: Mem(52), Val(1)
      linkObjPositionTo: (PLAYER)
      Unknown1165: s32'Ball_StingerAim'
      endIf: 
    ifOperation: (IS_EQUAL), Mem(115), Val(2)
      callSubroutine: s32'VeBallFlagAdd', 0, 128, 0, 0, 0, 0, 0, 0
      storeValue: Mem(45), Val(0)
      resetVelocity: 1
      storeValue: Mem(52), Val(1)
      Unknown1165: s32'Ball_CarcassRaidC'
      endIf: 
    ifOperation: (IS_EQUAL), Mem(115), Val(3)
      callSubroutine: s32'VeBallFlagAdd', 0, 128, 0, 0, 0, 0, 0, 0
      storeValue: Mem(45), Val(0)
      resetVelocity: 1
      storeValue: Mem(52), Val(1)
      linkObjPositionTo: (PLAYER)
      Unknown2185: 1
      Unknown1165: s32'Ball_CarcassRaidD'
      endIf: 
    ifOperation: (IS_EQUAL), Mem(115), Val(4)
      storeValue: Mem(45), Val(0)
      resetVelocity: 1
      storeValue: Mem(52), Val(1)
      linkObjPositionTo: (PLAYER)
      storeValue: Mem(47), Val(600)
      storeValue: Mem(48), Val(5)
      Unknown2241: 0, 2000
      Unknown449: s32'ven_ball_ex_hatudo', 100
      callSubroutine: s32'VeBallFlagAdd', 0, 16384, 0, 0, 0, 0, 0, 0
      Unknown1165: s32'Ball_Gold'
      endIf: 
    upon: (AFTER_EXIT)
      ifOperation: (IS_EQUAL), Mem(52), Val(1)
        linkObjPositionTo: (NULL)
        storeValue: Mem(52), Val(0)
        storeValue: Mem(47), Val(5)
        endIf: 
      endUpon: 
    upon: (FRAME_STEP)
      ifOperation: 5, Mem(45), Mem(51)
        callSubroutine: s32'VeBallMoveToTarget', 0, 0, 0, 0, 0, 0, 0, 0
        endIf: 
      if: Mem(46)
        ifOperation: (IS_LESSER), Mem(18), Val(100000)
          ifOperation: 16, Mem(13), Val(10)
            Unknown2143: 3, 123
            endIf: 
          endIf: 
        ifOperation: (IS_EQUAL), Mem(69), Val(1)
          createObject2: s32'BallZanzoh', 100
          endIf: 
        endIf: 
      callSubroutine: s32'VeBallCheckCeiling', 0, 0, 0, 0, 0, 0, 0, 0
      if: Mem(47)
        modifyVar: (ADD), Mem(47), Val(-1)
        ifNot: Mem(47)
          Unknown2176: 23
          endIf: 
        endIf: 
      if: Mem(53)
        modifyVar: (ADD), Mem(53), Val(-1)
        endIf: 
      if: Mem(54)
        ifNot: Mem(53)
          Unknown2176: 23
          endIf: 
        endIf: 
      ifOperation: (IS_EQUAL), Mem(48), Val(2)
        ifNot: Mem(50)
          Unknown14: s32'Lv2'
          storeValue: Mem(48), Val(0)
          storeValue: Mem(69), Val(2)
          endIf: 
        endIf: 
      ifOperation: (IS_EQUAL), Mem(48), Val(3)
        ifNot: Mem(50)
          Unknown14: s32'Lv3'
          storeValue: Mem(48), Val(0)
          storeValue: Mem(69), Val(3)
          endIf: 
        endIf: 
      ifOperation: (IS_EQUAL), Mem(48), Val(4)
        ifNot: Mem(50)
          Unknown14: s32'Lv4'
          storeValue: Mem(48), Val(0)
          storeValue: Mem(69), Val(4)
          endIf: 
        endIf: 
      ifOperation: (IS_EQUAL), Mem(48), Val(5)
        ifNot: Mem(50)
          Unknown14: s32'Lv5'
          storeValue: Mem(48), Val(0)
          storeValue: Mem(69), Val(5)
          endIf: 
        endIf: 
      ifOperation: (IS_GREATER), Mem(13), Val(180)
        Unknown1603: 1
        endIf: 
      if: Mem(49)
        Unknown60: 0x17000000640000000500000064000000
        ifOperation: (IS_LESSER_OR_EQUAL), Mem(ACCUMULATOR), Val(100000)
          Unknown178: 5
          Unknown41: 5
          modifyVar: (ADD), Mem(70), Val(1)
          callCmnEfFunc: s32'BallScaleUpdate'
          modifyVar: (ADD), Mem(53), Val(90)
          Unknown2320: s32'BishopKyusyu'
          Unknown40: 
          Unknown448: s32'ven_ball_ex_vacuum', 100
          deactivateObj: (SELF)
          endIf: 
        endIf: 
      endUpon: 
    upon: (BEFORE_EXIT)
      Unknown1603: 1
      endUpon: 
    endUpon: 
  sprite: s32'vee2_00', 6
  sprite: s32'vee2_00', 2147483647
  storeValue: Mem(51), Val(1)
  Unknown3: 
  exitState: 
  setMarker: s32'Lv2'
  sprite: s32'vee4_11', 5
  linkParticleEx: s32'ven_ball_lv2'
  setObjectSize: 500
  Unknown191: 120
  sprite: s32'vee4_11', 2
  setObjectSize: 1200
  Unknown191: -200
  sprite: s32'vee4_11', 2
  Unknown191: 200
  sprite: s32'vee4_11', 2147483647
  setObjectSize: 1000
  Unknown191: 0
  Unknown3: 
  exitState: 
  setMarker: s32'Lv3'
  sprite: s32'vee5_01', 5
  linkParticleEx: s32'ven_ball_lv3'
  setObjectSize: 500
  Unknown191: 120
  sprite: s32'vee5_01', 2
  setObjectSize: 1200
  Unknown191: -200
  sprite: s32'vee5_01', 2
  Unknown191: 200
  sprite: s32'vee5_01', 2147483647
  setObjectSize: 1000
  Unknown191: 0
  Unknown3: 
  exitState: 
  setMarker: s32'Lv4'
  sprite: s32'vee5_01', 5
  linkParticleEx: s32'ven_ball_lv4'
  setObjectSize: 500
  Unknown191: 120
  sprite: s32'vee5_01', 2
  setObjectSize: 1200
  Unknown191: -200
  sprite: s32'vee5_01', 2
  Unknown191: 200
  sprite: s32'vee5_01', 2147483647
  setObjectSize: 1000
  Unknown191: 0
  Unknown3: 
  exitState: 
  setMarker: s32'Lv5'
  callCmnEfFunc: s32'BallReset'
  storeValue: Mem(54), Val(1)
  sprite: s32'vee2_00gold', 2147483647
  if: Mem(152)
    storeValue: Mem(53), Val(288)
    endIf: 
  else: 
    storeValue: Mem(53), Val(240)
    endElse: 
  Unknown59: s32'TRP_VEN', 2, 157
  if: Mem(157)
    modifyVar: (ADD), Mem(70), Mem(157)
    modifyVar: (MUL), Mem(157), Val(90)
    modifyVar: (ADD), Mem(53), Mem(157)
    callCmnEfFunc: s32'BallScaleUpdate'
    endIf: 
  storeValue: Mem(47), Val(0)
  Unknown58: 0
  Unknown1602: 2
  Unknown1603: 1
  deactivateObj: (STACK_0)
  storeValue: Mem(46), Val(0)
  Unknown111: 60
  multiplyYVelocityByPercent: 60
  Unknown1883: 
  callSubroutine: s32'VeBallFlagDel', 0, -1, 0, 0, 0, 0, 0, 0
  callSubroutine: s32'VeBallFlagAdd', 0, 2, 0, 0, 0, 0, 0, 0
  linkParticleEx: s32'ven_ball_ex'
  resetVelocity: 1
  storeValue: Mem(69), Val(5)
  Unknown2180: 0
  Unknown2181: 0
  Unknown2182: 0
  Unknown2183: 0
  upon: (HIT_OR_GUARD)
    callSubroutine: s32'VeBallAngleReverseWall', 0, 0, 0, 0, 0, 0, 0, 0
    callSubroutine: s32'VeBallPerSpeed', 0, 100, 0, 0, 0, 0, 0, 0
    callSubroutine: s32'VeBallFlagDel', 0, -1, 0, 0, 0, 0, 0, 0
    Unknown1883: 
    Unknown14: s32'GoldSpin'
    endUpon: 
  Unknown3: 
  exitState: 
  setMarker: s32'Attack'
  callCmnEfFunc: s32'BallReset'
  playCharacterSFX: s32'1'
  Unknown58: 1
  Unknown13: s32'AttackLv2', 9, 2, 69, 0, 2
  Unknown13: s32'AttackLv3', 9, 2, 69, 0, 3
  Unknown13: s32'AttackLv4', 9, 2, 69, 0, 4
  Unknown13: s32'AttackLv5', 9, 2, 69, 0, 5
  sprite: s32'keep', 300
  hit: 
  Unknown1058: 0
  deactivateObj: (STACK_0)
  createObject2: s32'BallAura', 100
  setObjectToStackSlot: (STACK_0), (PREVIOUS)
  Unknown3: 
  exitState: 
  setMarker: s32'AttackLv2'
  sprite: s32'keep', 2
  numberOfHits: 2
  hit: 
  Unknown1058: 0
  deactivateObj: (STACK_0)
  createObject2: s32'BallAuraLv2', 100
  setObjectToStackSlot: (STACK_0), (PREVIOUS)
  Unknown1112: 0
  Unknown1110: 1
  Unknown1153: 1
  attackLevel: 4
  hitPushbackX: 50
  linkParticleEx: s32'ven_ball_lv2'
  setMarker: s32'loopLv2'
  sprite: s32'keep', 2
  hit: 
  Unknown3: 
  goToMarker: s32'loopLv2'
  Unknown3: 
  exitState: 
  setMarker: s32'AttackLv3'
  sprite: s32'keep', 2
  hit: 
  Unknown1058: 0
  deactivateObj: (STACK_0)
  createObject2: s32'BallAuraLv3', 100
  setObjectToStackSlot: (STACK_0), (PREVIOUS)
  Unknown1112: 0
  Unknown1110: 1
  Unknown1153: 1
  attackLevel: 4
  hitPushbackX: 50
  numberOfHits: 3
  linkParticleEx: s32'ven_ball_lv3'
  setMarker: s32'loopLv3'
  sprite: s32'keep', 2
  hit: 
  Unknown3: 
  goToMarker: s32'loopLv3'
  exitState: 
  setMarker: s32'AttackLv4'
  sprite: s32'keep', 1
  hit: 
  Unknown1058: 0
  deactivateObj: (STACK_0)
  createObject2: s32'BallAuraLv4', 100
  setObjectToStackSlot: (STACK_0), (PREVIOUS)
  Unknown1112: 0
  Unknown1110: 1
  Unknown1153: 1
  attackLevel: 4
  hitPushbackX: 50
  numberOfHits: 6
  linkParticleEx: s32'ven_ball_lv4'
  setMarker: s32'loopLv4'
  sprite: s32'keep', 1
  hit: 
  Unknown3: 
  goToMarker: s32'loopLv4'
  exitState: 
  setMarker: s32'AttackLv5'
  sprite: s32'keep', 300
  hit: 
  Unknown1058: 0
  hitEffectFlame: 1
  attackLevel: 4
  deactivateObj: (STACK_0)
  setObjectToStackSlot: (STACK_0), (PREVIOUS)
  callSubroutine: s32'VeBallSpeedByWallBound', 0, 9, 0, 13, 0, 0, 0, 0
  callSubroutine: s32'VeBallFlagAdd', 0, 1792, 0, 0, 0, 0, 0, 0
  Unknown3: 
  exitState: 
  setMarker: s32'Spin'
  callCmnEfFunc: s32'BallReset'
  callSubroutine: s32'VeBallFlagAdd', 0, 8960, 0, 0, 0, 0, 0, 0
  storeValue: Mem(50), Val(0)
  Unknown1165: s32'Ball_Spin'
  ifOperation: (IS_GREATER_OR_EQUAL), Mem(69), Val(3)
    Unknown2234: s32'vee5_01'
    setObjectSize: 1000
    linkParticleEx: s32'ven_ball_lv4'
    storeValue: Mem(69), Val(4)
    createObject2: s32'obj_ven_ballend_lv4', 100
    endIf: 
  ifOperation: (IS_EQUAL), Mem(69), Val(2)
    Unknown2234: s32'vee5_01'
    setObjectSize: 1000
    linkParticleEx: s32'ven_ball_lv3'
    storeValue: Mem(69), Val(3)
    createObject2: s32'obj_ven_ballend_lv3', 100
    endIf: 
  ifOperation: (IS_EQUAL), Mem(69), Val(1)
    Unknown2234: s32'vee4_11'
    setObjectSize: 1000
    linkParticleEx: s32'ven_ball_lv2'
    storeValue: Mem(69), Val(2)
    createObject2: s32'obj_ven_ballend_lv2', 100
    endIf: 
  sprite: s32'keep', 1
  storeValue: Mem(47), Val(360)
  Unknown58: 0
  Unknown1603: 1
  deactivateObj: (STACK_0)
  storeValue: Mem(46), Val(0)
  callSubroutine: s32'VeBallPerSpeed', 0, 60, 0, 0, 0, 0, 0, 0
  Unknown1883: 
  sprite: s32'keep', 1
  callSubroutine: s32'VeBallPerSpeed', 0, 98, 0, 0, 0, 0, 0, 0
  sprite: s32'keep', 1
  callSubroutine: s32'VeBallPerSpeed', 0, 98, 0, 0, 0, 0, 0, 0
  sprite: s32'keep', 1
  callSubroutine: s32'VeBallPerSpeed', 0, 98, 0, 0, 0, 0, 0, 0
  sprite: s32'keep', 1
  callSubroutine: s32'VeBallPerSpeed', 0, 98, 0, 0, 0, 0, 0, 0
  sprite: s32'keep', 1
  callSubroutine: s32'VeBallPerSpeed', 0, 98, 0, 0, 0, 0, 0, 0
  sprite: s32'keep', 1
  callSubroutine: s32'VeBallPerSpeed', 0, 98, 0, 0, 0, 0, 0, 0
  callSubroutine: s32'VeBallFlagDel', 0, -8961, 0, 0, 0, 0, 0, 0
  callSubroutine: s32'VeBallFlagAdd', 0, 2, 0, 0, 0, 0, 0, 0
  callSubroutine: s32'VeBallFlagAdd', 0, 64, 0, 0, 0, 0, 0, 0
  sprite: s32'keep', 1
  callSubroutine: s32'VeBallPerSpeed', 0, 98, 0, 0, 0, 0, 0, 0
  sprite: s32'keep', 1
  callSubroutine: s32'VeBallPerSpeed', 0, 98, 0, 0, 0, 0, 0, 0
  sprite: s32'keep', 1
  callSubroutine: s32'VeBallPerSpeed', 0, 98, 0, 0, 0, 0, 0, 0
  sprite: s32'keep', 1
  callSubroutine: s32'VeBallPerSpeed', 0, 98, 0, 0, 0, 0, 0, 0
  sprite: s32'keep', 1
  callSubroutine: s32'VeBallPerSpeed', 0, 98, 0, 0, 0, 0, 0, 0
  sprite: s32'keep', 1
  callSubroutine: s32'VeBallPerSpeed', 0, 98, 0, 0, 0, 0, 0, 0
  sprite: s32'keep', 1
  callSubroutine: s32'VeBallPerSpeed', 0, 98, 0, 0, 0, 0, 0, 0
  sprite: s32'keep', 1
  callSubroutine: s32'VeBallFlagDel', 0, 64, 0, 0, 0, 0, 0, 0
  callSubroutine: s32'VeBallPerSpeed', 0, 98, 0, 0, 0, 0, 0, 0
  sprite: s32'keep', 1
  callSubroutine: s32'VeBallPerSpeed', 0, 98, 0, 0, 0, 0, 0, 0
  sprite: s32'keep', 1
  callSubroutine: s32'VeBallPerSpeed', 0, 98, 0, 0, 0, 0, 0, 0
  sprite: s32'keep', 1
  callSubroutine: s32'VeBallPerSpeed', 0, 98, 0, 0, 0, 0, 0, 0
  sprite: s32'keep', 1
  callSubroutine: s32'VeBallPerSpeed', 0, 98, 0, 0, 0, 0, 0, 0
  sprite: s32'keep', 1
  callSubroutine: s32'VeBallPerSpeed', 0, 98, 0, 0, 0, 0, 0, 0
  sprite: s32'keep', 5
  callSubroutine: s32'VeBallPerSpeed', 0, 50, 0, 0, 0, 0, 0, 0
  sprite: s32'keep', 1
  callSubroutine: s32'VeBallPerSpeed', 0, 0, 0, 0, 0, 0, 0, 0
  sprite: s32'keep', 360
  sprite: s32'keep', 2147483647
  Unknown2176: 23
  Unknown3: 
  exitState: 
  setMarker: s32'GoldSpin'
  callCmnEfFunc: s32'BallReset'
  callSubroutine: s32'VeBallFlagAdd', 0, 8960, 0, 0, 0, 0, 0, 0
  storeValue: Mem(50), Val(0)
  storeValue: Mem(54), Val(1)
  sprite: s32'keep', 1
  storeValue: Mem(47), Val(0)
  Unknown58: 0
  Unknown1603: 1
  deactivateObj: (STACK_0)
  storeValue: Mem(46), Val(0)
  callSubroutine: s32'VeBallPerSpeed', 0, 60, 0, 0, 0, 0, 0, 0
  Unknown1883: 
  linkParticleEx: s32'ven_ball_ex_cooldown'
  sprite: s32'keep', 1
  callSubroutine: s32'VeBallPerSpeed', 0, 98, 0, 0, 0, 0, 0, 0
  sprite: s32'keep', 1
  callSubroutine: s32'VeBallPerSpeed', 0, 98, 0, 0, 0, 0, 0, 0
  sprite: s32'keep', 1
  callSubroutine: s32'VeBallPerSpeed', 0, 98, 0, 0, 0, 0, 0, 0
  sprite: s32'keep', 1
  callSubroutine: s32'VeBallPerSpeed', 0, 98, 0, 0, 0, 0, 0, 0
  sprite: s32'keep', 1
  callSubroutine: s32'VeBallPerSpeed', 0, 98, 0, 0, 0, 0, 0, 0
  sprite: s32'keep', 1
  callSubroutine: s32'VeBallPerSpeed', 0, 98, 0, 0, 0, 0, 0, 0
  callSubroutine: s32'VeBallFlagDel', 0, -8961, 0, 0, 0, 0, 0, 0
  callSubroutine: s32'VeBallFlagAdd', 0, 64, 0, 0, 0, 0, 0, 0
  sprite: s32'keep', 1
  callSubroutine: s32'VeBallPerSpeed', 0, 98, 0, 0, 0, 0, 0, 0
  sprite: s32'keep', 1
  callSubroutine: s32'VeBallPerSpeed', 0, 98, 0, 0, 0, 0, 0, 0
  sprite: s32'keep', 1
  callSubroutine: s32'VeBallPerSpeed', 0, 98, 0, 0, 0, 0, 0, 0
  sprite: s32'keep', 1
  callSubroutine: s32'VeBallPerSpeed', 0, 98, 0, 0, 0, 0, 0, 0
  sprite: s32'keep', 1
  callSubroutine: s32'VeBallPerSpeed', 0, 98, 0, 0, 0, 0, 0, 0
  sprite: s32'keep', 1
  callSubroutine: s32'VeBallPerSpeed', 0, 98, 0, 0, 0, 0, 0, 0
  sprite: s32'keep', 1
  callSubroutine: s32'VeBallPerSpeed', 0, 98, 0, 0, 0, 0, 0, 0
  sprite: s32'keep', 1
  callSubroutine: s32'VeBallFlagDel', 0, 64, 0, 0, 0, 0, 0, 0
  callSubroutine: s32'VeBallPerSpeed', 0, 98, 0, 0, 0, 0, 0, 0
  sprite: s32'keep', 1
  callSubroutine: s32'VeBallPerSpeed', 0, 98, 0, 0, 0, 0, 0, 0
  sprite: s32'keep', 1
  callSubroutine: s32'VeBallPerSpeed', 0, 98, 0, 0, 0, 0, 0, 0
  sprite: s32'keep', 1
  callSubroutine: s32'VeBallPerSpeed', 0, 98, 0, 0, 0, 0, 0, 0
  sprite: s32'keep', 1
  callSubroutine: s32'VeBallPerSpeed', 0, 98, 0, 0, 0, 0, 0, 0
  sprite: s32'keep', 1
  callSubroutine: s32'VeBallPerSpeed', 0, 98, 0, 0, 0, 0, 0, 0
  sprite: s32'keep', 5
  callSubroutine: s32'VeBallPerSpeed', 0, 50, 0, 0, 0, 0, 0, 0
  sprite: s32'keep', 1
  callSubroutine: s32'VeBallPerSpeed', 0, 0, 0, 0, 0, 0, 0, 0
  sprite: s32'keep', 1
  callSubroutine: s32'VeBallFlagAdd', 0, 2, 0, 0, 0, 0, 0, 0
  linkParticleEx: s32'ven_ball_ex'
  sprite: s32'keep', 360
  sprite: s32'keep', 2147483647
  Unknown2176: 23
  Unknown3: 
  exitState: 
  setMarker: s32'Homing'
  callCmnEfFunc: s32'BallReset'
  callSubroutine: s32'VeBallFlagDel', 0, -1, 0, 0, 0, 0, 0, 0
  sprite: s32'keep', 120
  Unknown1997: 0x0100000005000000640000000000000000000000000000000000000000000000D00700000000000064000000
  storeValue: Mem(49), Val(1)
  Unknown3: 
  exitState: 
  endState: 

beginState: s32'BallAura'
  sprite: s32'null', 2147483647
  linkObjPositionTo: (PARENT)
  Unknown457: (PARENT)
  linkParticleEx: s32'ven_ballaura'
  endState: 

beginState: s32'BallAuraLv2'
  sprite: s32'null', 2147483647
  linkObjPositionTo: (PARENT)
  Unknown457: (PARENT)
  linkParticleEx: s32'ven_ballaura_lv2'
  endState: 

beginState: s32'BallAuraLv3'
  sprite: s32'null', 2147483647
  linkObjPositionTo: (PARENT)
  Unknown457: (PARENT)
  linkParticleEx: s32'ven_ballaura_lv3'
  endState: 

beginState: s32'BallAuraLv4'
  sprite: s32'null', 2147483647
  linkObjPositionTo: (PARENT)
  Unknown457: (PARENT)
  linkParticleEx: s32'ven_ballaura_lv4'
  endState: 

beginState: s32'BallZanzoh'
  sprite: s32'null', 5
  linkParticleEx: s32'ven_ball_zanzoh'
  Unknown369: 
  Unknown191: -34
  endState: 

beginState: s32'BallDelete'
  sprite: s32'null', 20
  linkParticleEx: s32'ven_ballend'
  Unknown191: -50
  resetVelocity: 1
  endState: 

beginState: s32'ThrowBallEffect'
  upon: (IMMEDIATE)
    upon: (FRAME_STEP)
      callSubroutine: s32'BallMofCheck', 0, 0, 0, 0, 0, 0, 0, 0
      endUpon: 
    endUpon: 
  sprite: s32'vee5_01', 16
  Unknown2004: 22, 103
  linkObjPositionTo: (ENEMY)
  linkParticleEx: s32'ven_ballin'
  sprite: s32'vee5_01', 4
  sprite: s32'vee5_01', 2
  sprite: s32'vee5_01', 2
  sprite: s32'vee5_01', 2
  sprite: s32'vee5_01', 2
  Unknown41: 22
  Unknown2196: 0, 1
  Unknown40: 
  sprite: s32'vee5_01', 2
  sprite: s32'vee5_01', 2
  sprite: s32'vee5_01', 106
  setMarker: s32'end'
  sprite: s32'null', 1
  Unknown41: 22
  Unknown2196: 0, 0
  Unknown40: 
  Unknown449: s32'ven_ballin_end', 100
  endState: 

beginState: s32'ThrowBallEffectEnd'
  sprite: s32'null', 30
  linkParticleEx: s32'ven_ballend'
  Unknown2267: 6000
  Unknown2004: 22, 103
  linkObjPositionTo: (ENEMY)
  linkParticleEx: s32'ven_ballend'
  endState: 

beginState: s32'DarkAngelBallStart'
  sprite: s32'null', 64
  Unknown294: 1
  Unknown457: (PLAYER)
  linkObjPositionTo: (PLAYER)
  sprite: s32'null', 32
  linkParticleEx: s32'ven_darkangel_start'
  sprite: s32'null', 30
  Unknown457: (NULL)
  linkObjPositionTo: (NULL)
  sprite: s32'null', 100
  Unknown2161: 100, 0, 255000
  Unknown2247: 2, 115, 0, 0
  callEtcState: s32'DarkAngelBall', 130
  playCharacterSFX: s32'0'
  sprite: s32'null', 160
  endState: 

beginState: s32'DarkAngelBall'
  upon: (IMMEDIATE)
    Unknown245: 
    disableHitstop: 1
    attackLevel: 4
    Unknown1028: 3
    riscPlus: 3
    damage: 10
    stunValue: 0
    Unknown1137: 28
    if: Mem(115)
      damage: 12
      Unknown1177: 1
      Unknown1179: 1
      Unknown1137: 32
      Unknown1086: 30
      Unknown1165: s32'DarkAngelBallBurst'
      endIf: 
    hitPushbackX: 50
    untechableTime: 60
    hitAirPushbackY: 15750
    hitAirPushbackX: 10500
    riscMinus: 2
    Unknown1045: 4, s32'cmn_hit_sp_renzoku'
    if: Mem(126)
      guardType: (NONE)
      endIf: 
    Unknown58: 1
    numberOfHits: 34
    Unknown2180: 1
    Unknown2181: 1
    Unknown2182: 1
    Unknown2183: 1
    upon: (ON_DESTROY)
      linkParticleEx: s32'ven_darkangel_end'
      Unknown111: 60
      endUpon: 
    upon: (HIT)
      if: Mem(115)
        ifNot: Mem(45)
          storeValue: Mem(45), Val(1)
          Unknown2130: 5000
          endIf: 
        endIf: 
      endUpon: 
    endUpon: 
  sprite: s32'vee7_08', 2
  linkParticleEx: s32'ven_darkangel'
  sprite: s32'keep', 2
  sprite: s32'keep', 2
  sprite: s32'keep', 2
  physicsXImpulse: 0
  Unknown120: 175
  Unknown3: 
  setMarker: s32'loop'
  sprite: s32'keep', 3
  hit: 
  sprite: s32'keep', 3
  hit: 
  sprite: s32'keep', 3
  hit: 
  sprite: s32'keep', 3
  hit: 
  sprite: s32'keep', 3
  hit: 
  hitAirPushbackX: 15750
  sprite: s32'keep', 3
  hit: 
  Unknown3: 
  goToMarker: s32'loop'
  endState: 

beginState: s32'Barrier'
  upon: (IMMEDIATE)
    linkParticleEx: s32'ven_barrier'
    linkObjPositionTo: (PLAYER)
    upon: (AFTER_EXIT)
      deactivateObj: (SELF)
      endUpon: 
    upon: 30
      Unknown14: s32'End'
      endUpon: 
    Unknown243: 
    setObjectSize: 800
    endUpon: 
  setMarker: s32'loop'
  sprite: s32'vee_barrier', 1
  hit: 
  Unknown1028: 3
  Unknown1152: 1
  goToMarker: s32'loop'
  Unknown3: 
  setMarker: s32'End'
  sprite: s32'null', 10
  Unknown190: 70
  Unknown191: -50
  endState: 

beginState: s32'Neoblitz_atk'
  upon: (IMMEDIATE)
    Unknown457: (PARENT)
    linkObjPositionTo: (PARENT)
    linkParticleEx: s32'ven_neoblitz'
    endUpon: 
  sprite: s32'null', 80
  endState: 

beginState: s32'BG_ichigeki'
  upon: (IMMEDIATE)
    Unknown457: (PLAYER)
    linkParticleEx: s32'ven_ichigeki_bg'
    endUpon: 
  sprite: s32'null', 2147483647
  endState: 

beginState: s32'IchigekiBall'
  upon: (IMMEDIATE)
    Unknown457: (PLAYER)
    linkPawnWithAnim: s32'iball', s32'ichigeki_ball'
    Unknown2021: 0
    endUpon: 
  sprite: s32'null', 2147483647
  endState: 

beginState: s32'BG_ichigeki_hole'
  upon: (IMMEDIATE)
    linkObjPositionTo: (PLAYER)
    Unknown456: (PLAYER)
    Unknown457: (PLAYER)
    linkParticleEx: s32'ven_ichigeki_hole'
    endUpon: 
  sprite: s32'null', 2147483647
  endState: 

beginState: s32'ACEvtVEN_7A'
  upon: (IMMEDIATE)
    Unknown2114: -16777216, -16777216, 1
    Unknown2107: 0x4576656E745374616E640000000000000000000000000000000000000000000000000000
    Unknown2107: 0x4576656E745374616E640000000000000000000000000000000000000000000001000000
    endUpon: 
  sprite: s32'null', 1
  Unknown2123: s32'BGM_HEIJI2'
  Unknown2123: s32'BGM_Prospect'
  Unknown2122: 
  sprite: s32'null', 1
  Unknown2120: 0x4845494A4932000000000000000000000000000000000000000000000000000000000000
  Unknown2115: 40, 0
  sprite: s32'null', 90
  Unknown2113: 0x4143325F56454E5F4237415F3030315F3000000000000000000000000000000080020000680100003C000000B40000003C000000
  sprite: s32'null', 140
  Unknown2114: -16777216, 0, 60
  sprite: s32'null', 2147483647
  Unknown2106: 0x4143325F56454E5F4237415F30303200000000000000000000000000000000001E000000
  sprite: s32'null', 2147483647
  Unknown2106: 0x4143325F56454E5F4237415F303033000000000000000000000000000000000032000000
  sprite: s32'null', 2147483647
  Unknown2106: 0x4143325F56454E5F4237415F30303400000000000000000000000000000000001E000000
  sprite: s32'null', 2147483647
  Unknown2107: 0x4576656E7456454E3037415F303100000000000000000000000000000000000000000000
  Unknown2106: 0x4143325F56454E5F4237415F30303500000000000000000000000000000000001E000000
  sprite: s32'null', 2147483647
  Unknown2107: 0x4576656E7456454E3037415F303100000000000000000000000000000000000001000000
  Unknown2106: 0x4143325F56454E5F4237415F30303600000000000000000000000000000000001E000000
  sprite: s32'null', 10
  sprite: s32'null', 10
  Unknown2114: 0, -16777216, 10
  sprite: s32'null', 1
  Unknown2108: 
  endState: 

beginState: s32'ACEvtVEN_7B'
  upon: (IMMEDIATE)
    Unknown2114: -16777216, 0, 30
    Unknown2107: 0x4576656E7456454E3037425F303100000000000000000000000000000000000000000000
    Unknown2107: 0x4576656E745374616E640000000000000000000000000000000000000000000001000000
    endUpon: 
  sprite: s32'null', 1
  Unknown2120: 0x50726F737065637400000000000000000000000000000000000000000000000000000000
  Unknown2115: 50, 0
  sprite: s32'null', 2147483647
  Unknown2107: 0x4576656E7456454E3037425F303100000000000000000000000000000000000001000000
  Unknown2106: 0x4143325F56454E5F4237425F30303100000000000000000000000000000000001E000000
  sprite: s32'null', 2147483647
  Unknown2107: 0x4576656E7456454E3037425F303200000000000000000000000000000000000000000000
  Unknown2106: 0x4143325F56454E5F4237425F30303200000000000000000000000000000000001E000000
  sprite: s32'null', 2147483647
  Unknown2106: 0x4143325F56454E5F4237425F30303300000000000000000000000000000000001E000000
  sprite: s32'null', 2147483647
  Unknown2106: 0x4143325F56454E5F4237425F30303400000000000000000000000000000000001E000000
  sprite: s32'null', 2147483647
  Unknown2107: 0x4576656E7456454E3037425F303300000000000000000000000000000000000000000000
  Unknown2106: 0x4143325F56454E5F4237425F30303500000000000000000000000000000000001E000000
  sprite: s32'null', 2147483647
  Unknown2106: 0x4143325F56454E5F4237425F30303600000000000000000000000000000000001E000000
  sprite: s32'null', 2147483647
  Unknown2107: 0x4576656E7456454E3037425F303200000000000000000000000000000000000001000000
  Unknown2106: 0x4143325F56454E5F4237425F30303700000000000000000000000000000000001E000000
  sprite: s32'null', 2147483647
  Unknown2106: 0x4143325F56454E5F4237425F30303800000000000000000000000000000000001E000000
  sprite: s32'null', 2147483647
  Unknown2106: 0x4143325F56454E5F4237425F30303900000000000000000000000000000000001E000000
  sprite: s32'null', 10
  sprite: s32'null', 10
  Unknown2114: 0, -16777216, 10
  sprite: s32'null', 1
  Unknown2108: 
  endState: 

beginState: s32'ACEvtVEN_8A'
  upon: (IMMEDIATE)
    Unknown2114: -16777216, -16777216, 1
    Unknown2107: 0x4576656E745374616E640000000000000000000000000000000000000000000000000000
    Unknown2107: 0x4576656E7456454E3038415F303100000000000000000000000000000000000001000000
    endUpon: 
  sprite: s32'null', 1
  Unknown2123: s32'BGM_Hint'
  Unknown2123: s32'BGM_SeriousTalk'
  Unknown2122: 
  sprite: s32'null', 1
  Unknown2120: 0x48696E740000000000000000000000000000000000000000000000000000000000000000
  Unknown2115: 50, 0
  sprite: s32'null', 90
  Unknown2113: 0x4143325F56454E5F4238415F3030315F3000000000000000000000000000000080020000680100003C000000B40000003C000000
  sprite: s32'null', 140
  Unknown2114: -16777216, 0, 60
  sprite: s32'null', 2147483647
  Unknown2106: 0x4143325F56454E5F4238415F30303200000000000000000000000000000000001E000000
  sprite: s32'null', 2147483647
  Unknown2106: 0x4143325F56454E5F4238415F30303300000000000000000000000000000000001E000000
  sprite: s32'null', 2147483647
  Unknown2106: 0x4143325F56454E5F4238415F30303400000000000000000000000000000000001E000000
  sprite: s32'null', 2147483647
  Unknown2107: 0x4576656E7456454E3038415F303100000000000000000000000000000000000000000000
  Unknown2106: 0x4143325F56454E5F4238415F30303500000000000000000000000000000000001E000000
  sprite: s32'null', 2147483647
  Unknown2107: 0x4576656E7456454E3038415F303200000000000000000000000000000000000001000000
  Unknown2106: 0x4143325F56454E5F4238415F30303600000000000000000000000000000000001E000000
  sprite: s32'null', 10
  sprite: s32'null', 10
  Unknown2114: 0, -16777216, 10
  sprite: s32'null', 1
  Unknown2108: 
  endState: 

beginState: s32'ACEvtVEN_8B'
  upon: (IMMEDIATE)
    Unknown2114: -16777216, 0, 30
    Unknown2107: 0x4576656E745374616E640000000000000000000000000000000000000000000000000000
    Unknown2107: 0x4576656E7456454E3038425F303100000000000000000000000000000000000001000000
    endUpon: 
  sprite: s32'null', 1
  Unknown2120: 0x536572696F757354616C6B00000000000000000000000000000000000000000000000000
  Unknown2115: 50, 0
  sprite: s32'null', 2147483647
  Unknown2106: 0x4143325F56454E5F4238425F30303100000000000000000000000000000000001E000000
  sprite: s32'null', 2147483647
  Unknown2106: 0x4143325F56454E5F4238425F30303200000000000000000000000000000000001E000000
  sprite: s32'null', 2147483647
  Unknown2106: 0x4143325F56454E5F4238425F30303300000000000000000000000000000000001E000000
  sprite: s32'null', 10
  sprite: s32'null', 10
  Unknown2114: 0, -16777216, 10
  sprite: s32'null', 1
  Unknown2108: 
  endState: 

